### ISSUE TITLE
Add Scylla Manager and Scylla Monitoring to the CF tempalte

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-machine-image#10]
Scylla deployment often comes with Scylla Manager and Scylla Monitoring in place
It would be useful to run them by default from CF

**Comment by fruch** [comment]
Monitor should be quite easy, but manager is a bit of a pain, since you need one more scylla configured.

We can configure both on one node like we are doing in SCT

**Comment by tzach** [comment]
We can add them one by one
Starting with Monitoring make sense since its Open Source project

We can use AMI for each, as we do in Scylla Cloud

**Comment by yaronkaikov** [comment]
@tzach I wonder how many actually use our CF template and if is it worth the time to investigate it?
/cc @mykaul

**Comment by tzach** [comment]
I agree this become less relevant, as we are focusing on Scylla Cloud
