### ISSUE TITLE
aws: AMI image contains /root/.ssh/authorized_keys entry for Packer temporary SSH key

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla-machine-image#133]
Original issue was: scylladb/scylla-enterprise-machine-image#19

----

Seems like Packer AMI builder does not removed /root/.ssh/authorized_keys entry for Packer temporary SSH key.
Like this:
```
no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"centos\" rather than the user \"root\".';echo;sleep 10" ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkAvJqGkMv9cOQFLeOB96weCdh0SX656wrGwCVOjHqx49UW5Ybs2fjmmWQe7qoM0nO2qhN7pCYv6J6KGRq5fm9Qs/WJ2XcGqDGsyAplJGY6MUVO3pieEpsdiMHEGms70s1BLIV+cGuE6O1sscQWvv7Y3DITaq5D9aTGSEtbFZFrx36cmzcYX8J0sLPIsCjFCtAx3LXHpxJ1pS79AVs/ANjJE+9t1+GB7tSHyPpEctkJsMLIvX/4IRbgKSd/ouzTUxav1i3erI7kWR6YEEfbdW0I/fRbqLR1UuzZd4GbpC6X5wU12b+IOlHjA30AaROMIYJM6xbpAfTUnG2kiXWLBXP packer_6097c8cb-de03-7fed-6e2f-75a949a63f9c
```

It likely not a security risk since Packer delete temporary SSH key after AMI building, and also the entry does not access shell (*1), but it better to remove.
(*1: It is limited allowed command to `"echo 'Please login as the user \"centos\" rather than the user \"root\".';echo;sleep 10"`)

There is a option in Packer configuration to delete it, we can use this:
https://www.packer.io/docs/builders/amazon/ebs#ssh_clear_authorized_keys

**Comment by tzach** [comment]
similar issue https://github.com/hashicorp/packer/issues/3775
