### ISSUE TITLE
Azure image: scylla can't start due to missing AzureSnitch configuation

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-machine-image#138]
In https://github.com/scylladb/scylla-machine-image/pull/109 (currently under review) we will add support for Azure image.

Today we support in Scylla both AWS and GCE snitch. Need to add also Azure snitch - https://github.com/scylladb/scylla/issues/8593

**Comment by penberg** [comment]
@yaronkaikov I think you mentioned that alternative solution to `AzureSnitch` would be to generate the snitch properties file in machine-image at instance startup?

**Comment by yaronkaikov** [comment]
@penberg  yes, So we can do this , based on the information from the metadata output

**Comment by yaronkaikov** [comment]
Fixed by: https://github.com/scylladb/scylla/pull/9084
