### ISSUE TITLE
AWS Scylla Image - support T3 instances

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-machine-image#140]
We have some support for T2 for development mode

T2 instances are  EOL and are becomming less avail on AWS 

Need to consider which instance types need to be used instead of T2 (T3?)

**Comment by syuu1228** [comment]
@slivne @yaronkaikov T3 instances should be able to run in developer mode without error after we merged https://github.com/scylladb/scylla/commit/969c4258cf4a9c9bfdfb805050e61438cecbe932.

Note: even with developer mode, we cannot run our AMI without additional disks.
At least need to attach single EBS for /var/lib/scylla.

To force running scylla without additional disks, we need following operations:
```
sudo scylla_dev_mode_setup --developer-mode 1
sudo systemctl disable scylla-image-setup
sudo /opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic --ami
sudo systemctl start scylla-server
```

**Comment by syuu1228** [comment]
I found another problem related with no additional disks configuration: #255

**Comment by yaronkaikov** [comment]
@syuu1228 I have just started a `T3` instance with additional 100gb disk . and it's failing with  `t3 is not eligible for optimized automatic tuning!`

Although when i run `df -kh` i do see this mounted disk
```
scyllaadm@ip-10-0-4-24:~$ df -kh
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        30G  5.0G   25G  18% /
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           388M  812K  387M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/loop1       33M   33M     0 100% /snap/amazon-ssm-agent/2996
/dev/loop0       68M   68M     0 100% /snap/lxd/18150
/dev/loop2       32M   32M     0 100% /snap/snapd/10707
/dev/loop3       56M   56M     0 100% /snap/core18/1944
/dev/loop4       43M   43M     0 100% /snap/snapd/14066
/dev/loop5       56M   56M     0 100% /snap/core18/2253
/dev/loop6       62M   62M     0 100% /snap/core20/1242
/dev/loop7       25M   25M     0 100% /snap/amazon-ssm-agent/4046
tmpfs           388M     0  388M   0% /run/user/1000
/dev/loop8       68M   68M     0 100% /snap/lxd/21835
/dev/nvme1n1    100G  2.7G   98G   3% /var/lib/scylla
```

**Comment by roydahan** [comment]
I don't understand something, do we have anywhere any special treatment for t2?
t3 should behave exactly the same as t2.

**Comment by syuu1228** [comment]
@roydahan No, we don't need to do something special for T2 and T3.

**Comment by yaronkaikov** [comment]
@slivne Yes
