### ISSUE TITLE
Unattended upgrades enabled by default

### ISSUE THREAD

**Issue by adambabik** [scylladb/scylla-machine-image#152]
When additional software is installed on Ubuntu-based Scylla machine images, one may hit the following problem:

```
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 15976 (unattended-upgr)
```

Are unattended upgrades enabled by default due to some reason? What is the recommended way to disable it?

**Comment by avikivity** [comment]
They're probably auto-enabled by Ubuntu.

We have two options:
- disable auto-updates
- disable auto-updates for scylla* packages only

I guess we can start with a global disable.

**Comment by avikivity** [comment]
Updating scylla should be done deliberately, not automatically, since we need to go node by node and perform a graceful restart. Also need to leave the operator the possibility of downgrading if something foes goes wrong.

**Comment by adambabik** [comment]
That's one problem, the second is that anyone automating nodes management and installing additional software like Scylla Manager Agent will need to handle this case.

**Comment by nuivall** [comment]
They way I understand it this:
```
centos@scylla-cloud-node-5-f7eb49376589370cc120:/etc/apt/apt.conf.d$ cat 50unattended-upgrades
// Automatically upgrade packages from these (origin:archive) pairs
//
// Note that in Ubuntu security updates may pull in new dependencies
// from non-security sources (e.g. chromium). By allowing the release
// pocket these get automatically pulled in.
Unattended-Upgrade::Allowed-Origins {
	"${distro_id}:${distro_codename}";
	"${distro_id}:${distro_codename}-security";
	// Extended Security Maintenance; doesn't necessarily exist for
	// every release and this system may not have it installed, but if
	// available, the policy for updates is such that unattended-upgrades
	// should also install from here by default.
	"${distro_id}ESMApps:${distro_codename}-apps-security";
	"${distro_id}ESM:${distro_codename}-infra-security";
//	"${distro_id}:${distro_codename}-updates";
//	"${distro_id}:${distro_codename}-proposed";
//	"${distro_id}:${distro_codename}-backports";
};
```
it means only some distro packages are subject to this automated update.
