### ISSUE TITLE
GCP Image: Unattended upgrades enabled by default 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-machine-image#171]
#152 fix the issue for AWS images - we have the same issue in GCP images using ubuntu 20.04 as the base.

**Comment by slivne** [comment]
@syuu1228 the fix for 152 was in aws code - we need to fix the gcp image as well - please provide a fix.

Thanks

Shlomi

**Comment by syuu1228** [comment]
@slivne I think we should fix this issue by https://github.com/scylladb/scylla-machine-image/pull/132 (Merging AWS/GCP/Azure script into single script), because we are just trying to merge the PR.

**Comment by penberg** [comment]
@syuu1228 Let's fix this for GCE for easier backporting, and then do #132 after that.
