### ISSUE TITLE
Test failed because of 'elrepo' repository URL has been changed for CentOS7

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-machine-image#189]
AMI `ami-0d5aee59acfb93c8f)` (version 4.0.11) problem:

`elrepo` repository URL has been changed for CentOS7. Due this change `yum update` failes:
```
Command: 'sudo yum update -y --skip-broken'
Exit code: 1
Stdout:
Transaction Summary
================================================================================
Install    2 Packages (+1 Dependent package)
Upgrade  117 Packages
Total size: 297 M
Total download size: 65 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
Stderr:
Trying other mirror.
http://mirror.imt-systems.com/elrepo/archive/kernel/el7/x86_64/RPMS/python-perf-5.9.1-1.el7.elrepo.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
Error downloading packages:
python-perf-5.9.1-1.el7.elrepo.x86_64: [Errno 256] No more mirrors to try.
kernel-ml-5.9.1-1.el7.elrepo.x86_64: [Errno 256] No more mirrors to try.
kernel-ml-devel-5.9.1-1.el7.elrepo.x86_64: [Errno 256] No more mirrors to try.
```

Failed test: https://jenkins.scylladb.com/view/nexts/job/enterprise-2020.1/job/rolling-upgrade/job/rolling-upgrade-ami-test/40/console

**Comment by syuu1228** [comment]
elrepo-archive.repo is created by this commit: https://github.com/scylladb/scylla-machine-image/commit/708443337782b42f7c38dbe9c383a7d68d731f78
The commit is already reverted on recent releases, but this issue is about upgrading from older AMI, the file is still exists.
I guess we should document to suggest removing /etc/yum.repos.d/elrepo-archive.repo and then upgrade latest kernel-ml kernel.

see: https://github.com/scylladb/scylla/issues/7036

**Comment by slivne** [comment]
Thanks so this is not a blocker
 - lets test that the solution provided works 
 - we need a knowledgebase / faq / release notes so this will be fixed

**Comment by penberg** [comment]
The following steps unblock the upgrade for me:

```
sudo rm /etc/yum.repos.d/elrepo-archive.repo
sudo yum install https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
```

@syuu1228, can you please confirm that this is the kind of workaround you were thinking of?

**Comment by syuu1228** [comment]
@penberg Yes, suggested commands should fix the problem.
But even the problem fixed, the environment still has outdated kernel we used to pinning for workaround.
To resolve this, better to run
'yum --enablerepo=elrepo-kernel install kernel-ml' and 'reboot'.

**Comment by yaronkaikov** [comment]
Version 4.0.11 is EOL long time ago and we already switched to AMI's based on ubuntu:20.04
