### ISSUE TITLE
duplicate scylla-machine-image rpm from same relocatable package

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-machine-image#19]
There is a duplicate scylla-machine-image rpm and yaml file in the following link:
http://downloads.scylladb.com/rpm/unstable/centos/master/2020-03-09T21%3A59%3A53Z/scylla/noarch/
http://downloads.scylladb.com/rpm/unstable/centos/master/2020-03-09T21%3A59%3A53Z/

This happen when building cantos-rpm more then one from the same relocatable package

In such scenario, relevant packages should be overwritten same as scylla, scylla-jmx and scylla-tools

**Comment by yaronkaikov** [comment]
@fruch @bentsi FYI

**Comment by fruch** [comment]
@yaronkaikov stated he didn't reproduced it
