### ISSUE TITLE
Images (GCE, AMI, Azure): Align label/tag names

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla-machine-image#230]
We have similar tags/labels on the different images, defined on packer/scylla.json.
On azure and AMI: The tag/labels are camel case.
On GCE, they are with underscores.

AMI and Azure (except for the user_data)
```
      "tags": {
          "ScyllaVersion": "{{user `scylla_version`}}",
          "ScyllaMachineImageVersion": "{{user `scylla_machine_image_version`}}",
          "ScyllaJMXVersion": "{{user `scylla_jmx_version`}}",
          "ScyllaToolsVersion": "{{user `scylla_tools_version`}}",
          "ScyllaPython3Version": "{{user `scylla_python3_version`}}",
          "user_data_format_version": "2"
```
GCE:
```
      "image_labels":  {
          "scylla_version": "{{user `scylla_version`| clean_resource_name}}",
          "scylla_machine_image_version": "{{user `scylla_machine_image_version`| clean_resource_name}}",
          "scylla_jmx_version": "{{user `scylla_jmx_version`| clean_resource_name}}",
          "scylla_tools_version": "{{user `scylla_tools_version`| clean_resource_name}}",
          "scylla_python3_version": "{{user `scylla_python3_version`| clean_resource_name}}",
```

Align all to use camel case.

In addition, on GCE we added 
build-id and operating-system on #169. Done with dashes, due to QA request.
Need to align them on SCT too: https://github.com/scylladb/scylla-cluster-tests/issues/4022

**Comment by enaydanov** [comment]
CamelCase is not possible for GCE: https://cloud.google.com/compute/docs/labeling-resources#requirements

**Comment by hagitsegev** [comment]
Hmmm... only lowercase for GCE...
We need to think about some good solution for all, if possible. Maybe underscores?
AMI - Looks like yes: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions
Azure -  Looks OK. https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules 
GCE, as specified on above link - OK.

**Comment by yaronkaikov** [comment]
Closed with https://github.com/scylladb/scylla-machine-image/pull/283 and https://github.com/scylladb/scylla-machine-image/pull/284
