### ISSUE TITLE
Scylla machine Image support GCP e2 instances

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-machine-image#238]

**Comment by tzach** [comment]
@slivne is this for Scylla Cloud as a t2 equivalent?  other?

**Comment by syuu1228** [comment]
Since E2 instance type does not have local SSD, our machine image can run Scylla but show following message on login prompt:
```{type} is not eligible for optimized automatic tuning!
To continue startup ScyllaDB on this instance, run 'sudo scylla_io_setup' then 'systemctl start scylla-server'.```
And user need to run scylla_io_setup and start scylla-server manually, just same as T2, T3 instances on AWS EC2.

**Comment by syuu1228** [comment]
BTW we have a bug on login prompt for GCP, need to fix https://github.com/scylladb/scylla-machine-image/issues/259

**Comment by yaronkaikov** [comment]
@syuu1228 So we can close this, right?

**Comment by syuu1228** [comment]
@yaronkaikov Yes.
