### ISSUE TITLE
cloudformation: first instance should be node1

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylla-machine-image#252]
Currently, the first instance is created as node0.

**Comment by roydahan** [comment]
Can someone explain better what is this task?
(I see it's from 2021 and "Large")

**Comment by benipeled** [comment]
Semantic change only - the first node created by the CF stuck, named Node0 and it should be Node1
(the "Large" is a mistake)

But... for now, we're not going to move on with CF tasks unless we'll have a customer request
