### ISSUE TITLE
Add support of --raid-level parameter

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-machine-image#265]
Commit  https://github.com/scylladb/scylla/commit/42fd73d0332d034809c6cd228785bff82e1845aa added support to create
raid 5 by passing parameter --raid-leve to scylla_setup and scylla_raid_setup.

Need add support SMI scripts to create different raid configuration with aws ami and gce images

**Comment by yaronkaikov** [comment]
Closed via https://github.com/scylladb/scylla-machine-image/pull/266
