### ISSUE TITLE
root low disk space - cache using a lot of space

### ISSUE THREAD

**Issue by ricardoborenstein** [scylladb/scylla-machine-image#267]
On a customer monitoring the Active Alert raised and alert on root disk space. Once connected into the nodes we could identify that swap is using 16G

It should be cleaned

**Comment by slivne** [comment]
@ricardoborenstein its not clear what should be cleared and what you are not happy with

- please provide `df` of the node provide a full description of the issue 
- please describe the issue not what you want changed

**Comment by slivne** [comment]
please provide the image id and which scylla version you are running

**Comment by slivne** [comment]
I am closing the other issues https://github.com/scylladb/scylla-machine-image/issues/267 , https://github.com/scylladb/scylla-machine-image/issues/268 they are not informational a well

**Comment by yaronkaikov** [comment]
@ricardoborenstein Is this still relevant?we didn't get any information

**Comment by mykaul** [comment]
> @ricardoborenstein Is this still relevant?we didn't get any information

Closing.
