### ISSUE TITLE
root low disk usage - snap  using a lot of space

### ISSUE THREAD

**Issue by ricardoborenstein** [scylladb/scylla-machine-image#268]
On a customer monitoring the Active Alert raised and alert on root disk space. Once connected into the nodes we could identify that snap is using 1.5GB

If we don't use snap it can save up to 1.5GB 

```
support@$ sudo du -hs snap
1.5G    snap
```

**Comment by slivne** [comment]
we will handle on https://github.com/scylladb/scylla-machine-image/issues/267
