### ISSUE TITLE
Use sphinx-scylla-theme to generate the docs

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-machine-image#28]
https://github.com/scylladb/sphinx-scylla-theme is a Sphix theme similar to what we use in docs.scylladb.com

It will be nice to use it with the Sphinx project.

**Comment by yaronkaikov** [comment]
@tzach Do we still want to implement it?

**Comment by tzach** [comment]
No. The original motivation was to list the images per release; we are already doing that
https://opensource.docs.scylladb.com/stable/reference/aws-images.html
