### ISSUE TITLE
azure_instance class is broken

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla-machine-image#319]
azure_instance class does not have inherited abstract methods, causes Traceback:
```
>>> i = azure_instance()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't instantiate abstract class azure_instance with abstract methods instance_size, user_data
```

**Comment by yaronkaikov** [comment]
@syuu1228 i think the fix was done as part of https://github.com/scylladb/scylla-machine-image/pull/330, right? if yes, please close this issue

**Comment by syuu1228** [comment]
It fixed by https://github.com/scylladb/scylla-machine-image/pull/330, closing.
