### ISSUE TITLE
Setting up swapspace failed on symlink creation

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-machine-image#329]
## Installation details

Cluster size: 6 nodes (i3.2xlarge)

Scylla running with shards number (live nodes):
**No resources left at the end of the run**

OS / Image: `ami-036ff971553072cce ami-06cb779a9aa0b3693` (aws: eu-west-1)

Test: `rolling-upgrade-multi-dc-ami-test`

Test id: `57703427-77b4-49b4-a83a-35a79cb3e8f8`

Test name: `upgrade_test/rolling-upgrade-multi-dc-ami-test`

Test config file(s):

- [multi-dc-rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/e4c0bed30cedac33ef36d5d1e58e193669c3d2f5/test-cases/upgrades/multi-dc-rolling-upgrade.yaml)

## Issue description

It failed on one node (multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4) from 6 with **D-Bus connection terminated**.
```
Mar 05 04:15:36 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[8553]: Setting up swapspace version 1, size = 12.4 GiB (13260288000 bytes)
Mar 05 04:15:36 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[8553]: no label, UUID=7dcb4884-d970-48d2-823e-8372817f77c7
Mar 05 04:15:36 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[10134]: Created symlink /etc/systemd/system/multi-user.target.wants/swapfile.swap → /etc/systemd/system/swapfile.swap.
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[10169]: Warning! D-Bus connection terminated.
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[10169]: Failed to wait for response: Connection reset by peer
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[8340]: Traceback (most recent call last):
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[8340]:   File "/opt/scylladb/scripts/libexec/scylla_swap_setup", line 105, in <module>
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[8340]:     swap.start()
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[8340]:   File "/opt/scylladb/scripts/scylla_util.py", line 795, in start
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[8340]:     return run('systemctl {} start {}'.format(self.ctlparam, self._unit), shell=True, check=True)
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[8340]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[8340]:     raise CalledProcessError(retcode, process.args,
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[8340]: subprocess.CalledProcessError: Command 'systemctl  start swapfile.swap' returned non-zero exit status 1.
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[555]: Traceback (most recent call last):
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[555]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 41, in <module>
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[555]:     run('/opt/scylladb/scripts/scylla_swap_setup --swap-directory /', shell=True, check=True)
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[555]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[555]:     raise CalledProcessError(retcode, process.args,
Mar 05 04:15:37 multi-dc-rolling-upgrade-master-ubu-db-node-57703427-4 scylla_image_setup[555]: subprocess.CalledProcessError: Command '/opt/scylladb/scripts/scylla_swap_setup --swap-directory /' returned non-zero exit status 1.
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 57703427-77b4-49b4-a83a-35a79cb3e8f8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=57703427-77b4-49b4-a83a-35a79cb3e8f8)
- Show all stored logs command: `$ hydra investigate show-logs 57703427-77b4-49b4-a83a-35a79cb3e8f8`

## Logs:
- **db-cluster-57703427.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/57703427-77b4-49b4-a83a-35a79cb3e8f8/20220305_044614/db-cluster-57703427.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/57703427-77b4-49b4-a83a-35a79cb3e8f8/20220305_044614/db-cluster-57703427.tar.gz)
- **sct-runner-57703427.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/57703427-77b4-49b4-a83a-35a79cb3e8f8/20220305_044614/sct-runner-57703427.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/57703427-77b4-49b4-a83a-35a79cb3e8f8/20220305_044614/sct-runner-57703427.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-multi-dc-ami-test/30/)

**Comment by roydahan** [comment]
@yaronkaikov are you aware of it?

**Comment by yaronkaikov** [comment]
@syuu1228 Can you please have a look ?

**Comment by syuu1228** [comment]
The error is very unusual, `Warning! D-Bus connection terminated. Failed to wait for response: Connection reset by peer`  on systemctl probably means the connection to systemd is disconnected suddenly.
It may means systemd is dead on the instance, but I can't say more detail from only this log.

At least we can say the error is reported from systemctl, not our code. I found exactly same error message on systemd code:
https://github.com/systemd/systemd/blob/466f2351bbb5c0fdc9f153e35506570e59b14c5f/src/shared/bus-wait-for-jobs.c#L29

@avikivity any idea?

**Comment by avikivity** [comment]
Maybe systemd/dbus was restarted for a package upgrade. I suggest to close this as non-reproducible, and reopen+investigate if we see it again. Otherwise it's a waste of effort.

**Comment by yaronkaikov** [comment]
> Maybe systemd/dbus was restarted for a package upgrade. I suggest to close this as non-reproducible, and reopen+investigate if we see it again. Otherwise it's a waste of effort.

Closing
