### ISSUE TITLE
instance built with ami-4.4.9 could n't start due to (unnamed net_device) (uninitialized): Failed to submit get_feature command 12 error: -62

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-machine-image#332]
scylla ami: ami-0acfb885395ac4f8e(eu-north-1)
scylla version 4.4.9
Job: https://jenkins.scylladb.com/view/scylla-4.4/job/scylla-4.4/job/longevity/job/longevity-100gb-4h-test/
kernel version:` Linux longevity-100gb-4h-4-4-db-node-d2b1eac8-1 5.16.12-1.el7.elrepo.x86_64 #1 SMP PREEMPT Tue Mar 1 13:30:28 EST 2022 x86_64 x86_64 x86_64 GNU/Linux`
OS version: 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

Most of the jobs for 4.4.9 is failed.The main problem, job is terminated, because sct couldn't connect to instance during timeout.
in aws console such instance has 1 failed health check:
![Screenshot from 2022-03-09 04-22-10](https://user-images.githubusercontent.com/44991177/157516451-5ffa2f25-1459-4378-a443-92ccbc27a273.png)

i got access to console and see next error:
```
[    3.949925] ata1: PATA max MWDMA2 cmd 0x1f0 ctl 0x3f6 bmdma 0xc100 irq 14
[    3.958193] ata2: PATA max MWDMA2 cmd 0x170 ctl 0x376 bmdma 0xc108 irq 15
[    3.976336] nvme nvme0: pci function 0000:00:1d.0
[    3.980303] nvme nvme1: pci function 0000:00:1e.0
[    6.959636] ena 0000:00:03.0 (unnamed net_device) (uninitialized): The ena device sent a completion but the driver didn't receive a MSI-X interrupt (cmd 8), autopolling mode is OFF
[    6.971400] ena 0000:00:03.0 (unnamed net_device) (uninitialized): Failed to submit get_feature command 12 error: -62
[    6.979201] ena 0000:00:03.0: Cannot init indirect table
[    6.983387] ena 0000:00:03.0: Cannot init RSS rc: -62
[    6.989324] ena: probe of 0000:00:03.0 failed with error -62
[   64.112499] nvme nvme1: I/O 28 QID 0 timeout, completion polled
[   64.112523] nvme nvme0: I/O 24 QID 0 timeout, completion polled
[  125.553423] nvme nvme0: I/O 0 QID 0 timeout, completion polled
[  125.553427] nvme nvme1: I/O 8 QID 0 timeout, completion polled
```

The problem is relevant only for 4.4.9. scylla-4.4.8 doesn't have such issue

**Comment by yaronkaikov** [comment]
@syuu1228 Can you please take a look?

**Comment by syuu1228** [comment]
It sounds like ENA driver issue (unless nic device is broken), will take a look

**Comment by syuu1228** [comment]
> The problem is relevant only for 4.4.9. scylla-4.4.8 doesn't have such issue

Maybe it is because kernel version/ENA driver version difference.

**Comment by fruch** [comment]
@aleksbykov compare it to a machine booted with AMI without user-data

we might be breaking something while boot it taking place cause of the user-data

**Comment by aleksbykov** [comment]
@fruch i will check, but it failed during instance initialization, the user data is not yet loaded

**Comment by fruch** [comment]
> @fruch i will check, but it failed during instance initialization, the user data is not yet loaded

user-data is passed down during creating of an instance (much before we connect to it)

**Comment by syuu1228** [comment]
This bug report seems similar issue, different kernel though:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1961968
Anyway it likely kernel or driver bug

**Comment by syuu1228** [comment]
Seems like the commit "PCI/MSI: Mask MSI-X vectors only on success" is causing the bug:
- discussion on Ubuntu: https://lists.ubuntu.com/archives/kernel-team/2022-February/128268.html
- the commit: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=83dbf898a2d45289be875deb580e93050ba67529

And also I found same discussion on upstream (LKML), not only Ubuntu kernel:
- https://lore.kernel.org/lkml/c4a65b9a-d1e2-bf0d-2519-aac7185931d5@redhat.com/T/

So I think we should keep current workaround patch, and wait for the fix on kernel-ml package.

**Comment by yaronkaikov** [comment]
@syuu1228 Since rscylla-4.4 is EOL (4.6.0 was released), i think we can close this. it's related only to centos based images which we don't have any more
