### ISSUE TITLE
AWS i4i not supported out of the box

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-machine-image#342]
Need to recognize the instance family and tune I/O

**Comment by slivne** [comment]
https://aws.amazon.com/blogs/aws/new-storage-optimized-amazon-ec2-instances-i4i-powered-by-intel-xeon-scalable-ice-lake-processors/

**Comment by yaronkaikov** [comment]
Closes via https://github.com/scylladb/scylla-machine-image/pull/349
