### ISSUE TITLE
[AMI/GCP/Azure] - Align images name

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-machine-image#346]
Today we have different naming convention for our images 
### **In AMI:**
For building AMI via Jenkins in master branch we have:  `scylla_2022-05-01T14-26-06Z-build-312-x86_64` 
For building AMI locally we are getting: `scylla_2022-05-01T12-44-47Z-build-2022-05-01T12-44-46-`

Both image name doesn't make any sense, instead we need to check the tags to get more information

### **In GCP:** 
For building GCP via Jenkins in master branch we have: `scylla-5-1-dev-0-20220429-7f1e368e92ce-1-build-312`

### **In Azure:**
For building Azure image via Jenkins in master branch: `ScyllaDB-5.1.dev-0.20220427.f6ce7891a590-1-build-144`
For building images for debug (same branch): `debug-image-ScyllaDB-4.7.dev-0.20211119.f3d5b2b2b0-1-build-189`

Let's align all images name

**Comment by benipeled** [comment]
Suggested convention `<product>_<version>_<dev/debug>_<arch>`, ex.
- `scylla_5.1-dev.x86`
- `scylla_2022.1-dev.aarch64`
- `scylla_5.1-debug.x86` (we can use the `debug-image-` prefix for hydra backward compatibility)

All other information (date, build, commit, etc.) will be added as tags

**Comment by fgelcer** [comment]
> * `scylla_2022.1-dev.aarch64`

shouldn't it be `scylla_enterprise_2022.1-dev.aarch64`?

**Comment by yaronkaikov** [comment]
> > * `scylla_2022.1-dev.aarch64`
> 
> shouldn't it be `scylla_enterprise_2022.1-dev.aarch64`?

yes
