### ISSUE TITLE
scylla_cloud_io_setup doesn't have run premissions

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-machine-image#351]
## Issue description

booting of the AMI cause the following error:
```
May 03 11:52:02 artifacts-ami-jenkins-db-node-6570c7bb-1 scylla_image_setup[930]: Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
May 03 11:52:02 artifacts-ami-jenkins-db-node-6570c7bb-1 scylla_image_setup[916]: Devices: ['/dev/nvme0n1']
May 03 11:52:04 artifacts-ami-jenkins-db-node-6570c7bb-1 scylla_image_setup[5979]: /bin/sh: 1: /opt/scylladb/scylla-machine-image/scylla_cloud_io_setup: Permission denied
May 03 11:52:04 artifacts-ami-jenkins-db-node-6570c7bb-1 scylla_image_setup[513]: Traceback (most recent call last):
May 03 11:52:04 artifacts-ami-jenkins-db-node-6570c7bb-1 scylla_image_setup[513]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 29, in <module>
May 03 11:52:04 artifacts-ami-jenkins-db-node-6570c7bb-1 scylla_image_setup[513]:     cloud_instance.io_setup()
May 03 11:52:04 artifacts-ami-jenkins-db-node-6570c7bb-1 scylla_image_setup[513]:   File "/opt/scylladb/scylla-machine-image/lib/scylla_cloud.py", line 758, in io_setup
May 03 11:52:04 artifacts-ami-jenkins-db-node-6570c7bb-1 scylla_image_setup[513]:     run('/opt/scylladb/scylla-machine-image/scylla_cloud_io_setup', check=True, shell=True)
May 03 11:52:04 artifacts-ami-jenkins-db-node-6570c7bb-1 scylla_image_setup[513]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
May 03 11:52:04 artifacts-ami-jenkins-db-node-6570c7bb-1 scylla_image_setup[513]:     raise CalledProcessError(retcode, process.args,
May 03 11:52:04 artifacts-ami-jenkins-db-node-6570c7bb-1 scylla_image_setup[513]: subprocess.CalledProcessError: Command '/opt/scylladb/scylla-machine-image/scylla_cloud_io_setup' returned non-zero exit status 126.
May 03 11:52:04 artifacts-ami-jenkins-db-node-6570c7bb-1 systemd[1]: scylla-image-setup.service: Main process exited, code=exited, status=1/FAILURE
```

## Installation details

Cluster size: 1 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- artifacts-ami-jenkins-db-node-6570c7bb-1 (44.204.205.146 | 10.0.0.97) (shards: -1)

OS / Image: `ami-038b9479c558eeae7` (aws: us-east-1)

Test: `artifacts-ami-test`
Test id: `6570c7bb-cabf-4155-8b30-775480b0b3e0`
Test name: `scylla-master/artifacts/artifacts-ami-test`
Test config file(s):

- [ami.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/25a4739f0e46f1e7e9b86cecfefca5c78118799e/test-cases/artifacts/ami.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 6570c7bb-cabf-4155-8b30-775480b0b3e0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=6570c7bb-cabf-4155-8b30-775480b0b3e0)
- Show all stored logs command: `$ hydra investigate show-logs 6570c7bb-cabf-4155-8b30-775480b0b3e0`

## Logs:
- **db-cluster-6570c7bb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6570c7bb-cabf-4155-8b30-775480b0b3e0/20220503_115931/db-cluster-6570c7bb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6570c7bb-cabf-4155-8b30-775480b0b3e0/20220503_115931/db-cluster-6570c7bb.tar.gz)
- **sct-runner-6570c7bb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6570c7bb-cabf-4155-8b30-775480b0b3e0/20220503_115931/sct-runner-6570c7bb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6570c7bb-cabf-4155-8b30-775480b0b3e0/20220503_115931/sct-runner-6570c7bb.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ami-test/693/)

**Comment by yaronkaikov** [comment]
@fruch I have dropped https://github.com/scylladb/scylla-machine-image/pull/347 from next.
