### ISSUE TITLE
support cloud-init along with Scylla User Data

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-machine-image#357]
Currently scylla-mechine-image configure script takes over user-data and does not allow to use cloud-init compatible input.
This prevents from using feature rich cloud-init and replaces it with something limited only to scylla.
E.g. in SCT we would like to use cloud-init with .yaml formatted files (see https://cloudinit.readthedocs.io/en/latest/topics/examples.html)
to configure instances.
Also our customers might want to use cloud-init and not resign of using scylla-machine-image configuration.

Request is about adding support for cloud-init compatible scripts.
I have ideas on how to do it:
1. Create cloud-init module.
Will require module implementation and installation in proper place. Docs about creating modules: https://cloudinit.readthedocs.io/en/latest/topics/module_creation.html
2. As currently it is done but add yaml support to user-data and parse it.
3. Create separate Scylla configuration file
`cloud-init` .yaml files can define `write_files` section which allows users to create files at any place in the system. Idea is to use it to create scylla configuration json and use it instead of scylla specific user-data. This should be very easy and we could maintain backward compatibility (e.g. if we find `#cloud-config` preamble in user-data, use file, or just use file and if not found, fallback to current solution)

**Comment by soyacz** [comment]
@bentsi ^^

**Comment by fruch** [comment]
FYI, @yaronkaikov @syuu1228

@tzach, did we ever got requests/questions like this from customers ?

**Comment by soyacz** [comment]
@tzach @slivne If you agree we want this I'd be glad to implement it (option 3 - with backward compatibility).
