### ISSUE TITLE
i4i instance fails in artifact ami-test

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-machine-image#365]
## Installation details

Cluster size: 1 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- artifacts-ami-jenkins-db-node-b265aa32-1 (44.195.35.34 | 10.0.3.22) (shards: -1)

OS / Image: `ami-023436d4c20a0abc7` (aws: us-east-1)

Test: `artifacts-ami-test`
Test id: `b265aa32-844b-483e-b2fc-14c1d0571126`
Test name: `scylla-5.0/artifacts/artifacts-ami-test`
Test config file(s):

- [ami.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1a222e795bbf60731cac5be6df6d0c3bd2ae2e46/test-cases/artifacts/ami.yaml)

## Issue description

**File "/opt/scylladb/scylla-machine-image/libexec/scylla_cloud_io_setup", line 180, in <module>
Jun 03 04:13:02 artifacts-ami-jenkins-db-node-fe1e6bfb-1 scylla_image_setup[7043]:     elif idata.instancetype == "i4i.large":
Jun 03 04:13:02 artifacts-ami-jenkins-db-node-fe1e6bfb-1 scylla_image_setup[7043]: AttributeError: 'aws_instance' object has no attribute 'instancetype'**

- Restore Monitor Stack command: `$ hydra investigate show-monitor b265aa32-844b-483e-b2fc-14c1d0571126`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b265aa32-844b-483e-b2fc-14c1d0571126)
- Show all stored logs command: `$ hydra investigate show-logs b265aa32-844b-483e-b2fc-14c1d0571126`

## Logs:
- **db-cluster-b265aa32.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b265aa32-844b-483e-b2fc-14c1d0571126/20220603_023638/db-cluster-b265aa32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b265aa32-844b-483e-b2fc-14c1d0571126/20220603_023638/db-cluster-b265aa32.tar.gz)
- **sct-runner-b265aa32.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b265aa32-844b-483e-b2fc-14c1d0571126/20220603_023638/sct-runner-b265aa32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b265aa32-844b-483e-b2fc-14c1d0571126/20220603_023638/sct-runner-b265aa32.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/artifacts/job/artifacts-ami-test/166/)

**Comment by yaronkaikov** [comment]
Closed via https://github.com/scylladb/scylla-machine-image/pull/366/commits/407984ddb01929cdaae18ba78dd3869ca86cbafd
