### ISSUE TITLE
Cannot run scylla on supported instance without io preset (m5d for example)

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-machine-image#370]
When using supported instance (e.g. m5d) which has no io properties preset, Scylla fails to start due error:
```
ERROR:root:This is a supported AWS instance type but there are no preconfigured IO scheduler parameters for it.
```
Even if we manually provide io_properties.yaml and io.conf files it will always fail during `Scylla Cloud Image Setup` service.

**Comment by soyacz** [comment]
Maybe in case of supported instance, `scylla_io_setup` should be triggered automatically when preset is not available instead of raising an error?

**Comment by fruch** [comment]
> Maybe in case of supported instance, `scylla_io_setup` should be triggered automatically when preset is not available instead of raising an error?

It's call made long ago that we want the numbers to fixed (after it was tested and approved). 

What is the test case ? that we are using a non supported type ?

BTW the title is confusing, is this type supported or not ?

**Comment by soyacz** [comment]
According to code it is supported (see error message) - but we miss preset values for it.

So either we provide preconfigured values for all supported instances, or remove support. Another option would be running io_setup in that cases. Otherwise we cannot start Scylla.
Full test details:

## Installation details



Cluster size: 180 nodes (m5d.large)

Scylla Nodes used in this run:
- cluster-scale-test-5-0-db-node-881616f1-99 (13.53.216.59 | 10.0.3.10) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-98 (13.51.55.222 | 10.0.3.223) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-97 (13.53.173.4 | 10.0.1.91) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-96 (13.53.67.251 | 10.0.0.32) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-95 (16.16.68.90 | 10.0.3.134) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-94 (13.51.156.100 | 10.0.2.182) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-93 (16.170.230.37 | 10.0.2.40) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-92 (13.51.159.250 | 10.0.0.114) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-91 (13.48.55.28 | 10.0.2.171) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-90 (13.51.165.233 | 10.0.2.241) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-9 (13.51.235.78 | 10.0.2.229) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-89 (13.48.138.252 | 10.0.3.14) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-88 (13.48.84.198 | 10.0.3.4) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-87 (13.48.55.22 | 10.0.1.171) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-86 (13.48.138.3 | 10.0.0.116) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-85 (16.171.65.227 | 10.0.2.175) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-84 (13.51.64.48 | 10.0.3.37) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-83 (13.49.223.10 | 10.0.2.47) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-82 (16.16.27.130 | 10.0.3.192) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-81 (13.51.233.8 | 10.0.2.107) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-80 (16.171.64.215 | 10.0.2.104) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-8 (13.53.38.242 | 10.0.0.149) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-79 (13.49.46.19 | 10.0.0.181) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-78 (13.50.16.199 | 10.0.0.205) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-77 (13.49.75.114 | 10.0.0.46) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-76 (13.53.124.52 | 10.0.3.154) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-75 (16.170.157.19 | 10.0.3.108) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-74 (16.171.64.16 | 10.0.1.56) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-73 (13.49.21.184 | 10.0.0.39) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-72 (13.50.4.152 | 10.0.3.56) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-71 (13.53.190.244 | 10.0.1.61) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-70 (16.170.146.191 | 10.0.0.249) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-7 (13.53.116.34 | 10.0.0.111) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-69 (16.170.162.91 | 10.0.3.27) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-68 (16.171.52.216 | 10.0.1.139) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-67 (13.51.234.121 | 10.0.1.165) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-66 (16.16.63.174 | 10.0.1.163) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-65 (16.16.25.65 | 10.0.0.110) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-64 (13.53.216.34 | 10.0.2.144) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-63 (16.170.229.28 | 10.0.3.54) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-62 (13.51.234.222 | 10.0.0.50) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-61 (16.170.159.53 | 10.0.0.31) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-60 (13.48.133.19 | 10.0.2.131) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-6 (13.53.173.205 | 10.0.3.199) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-59 (13.50.4.183 | 10.0.2.76) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-58 (16.170.155.137 | 10.0.3.140) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-57 (13.53.37.2 | 10.0.0.63) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-56 (16.170.231.230 | 10.0.3.148) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-55 (13.53.198.56 | 10.0.3.238) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-54 (13.51.6.144 | 10.0.1.15) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-53 (13.49.0.202 | 10.0.1.223) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-52 (16.16.57.208 | 10.0.1.149) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-51 (13.49.73.11 | 10.0.2.23) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-50 (16.171.60.253 | 10.0.3.153) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-5 (16.170.158.200 | 10.0.1.75) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-49 (13.48.48.2 | 10.0.2.91) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-48 (13.49.76.223 | 10.0.0.79) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-47 (13.49.226.94 | 10.0.1.170) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-46 (16.16.57.155 | 10.0.2.27) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-45 (16.170.143.206 | 10.0.1.50) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-44 (13.53.35.233 | 10.0.2.242) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-43 (13.51.165.170 | 10.0.1.108) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-42 (13.51.13.48 | 10.0.1.34) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-41 (13.51.178.236 | 10.0.2.101) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-40 (13.51.159.193 | 10.0.0.170) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-4 (16.170.148.165 | 10.0.1.199) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-39 (13.49.75.47 | 10.0.0.62) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-38 (16.16.28.117 | 10.0.3.99) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-37 (13.53.216.128 | 10.0.2.122) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-36 (13.51.235.228 | 10.0.0.88) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-35 (16.170.229.64 | 10.0.2.41) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-34 (16.170.172.29 | 10.0.1.140) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-33 (13.53.173.31 | 10.0.2.197) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-32 (13.53.68.134 | 10.0.2.52) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-31 (13.49.80.240 | 10.0.0.139) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-30 (16.170.230.200 | 10.0.0.168) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-3 (13.48.138.126 | 10.0.1.45) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-29 (13.51.237.3 | 10.0.1.147) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-28 (13.49.246.200 | 10.0.0.177) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-27 (13.49.18.106 | 10.0.2.71) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-26 (16.170.140.150 | 10.0.1.121) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-25 (13.49.69.53 | 10.0.2.164) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-24 (13.51.173.40 | 10.0.1.249) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-23 (13.48.178.174 | 10.0.3.84) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-22 (16.16.65.103 | 10.0.0.186) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-21 (13.51.48.113 | 10.0.1.194) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-20 (13.51.69.75 | 10.0.3.78) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-2 (13.50.16.165 | 10.0.0.118) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-19 (16.170.158.164 | 10.0.3.40) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-180 (13.53.173.178 | 10.0.2.125) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-18 (16.170.234.247 | 10.0.0.163) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-179 (13.48.24.34 | 10.0.0.10) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-178 (16.170.221.147 | 10.0.1.74) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-177 (16.170.158.203 | 10.0.1.225) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-176 (16.16.64.44 | 10.0.3.109) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-175 (13.48.190.112 | 10.0.2.97) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-174 (16.16.66.94 | 10.0.3.126) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-173 (13.48.71.241 | 10.0.3.178) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-172 (13.51.234.151 | 10.0.3.224) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-171 (13.53.123.32 | 10.0.2.234) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-170 (16.16.64.148 | 10.0.2.82) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-17 (13.49.23.86 | 10.0.3.32) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-169 (13.51.174.208 | 10.0.3.75) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-168 (13.51.174.144 | 10.0.2.216) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-167 (13.49.223.181 | 10.0.0.198) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-166 (16.170.229.50 | 10.0.1.168) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-165 (13.48.106.226 | 10.0.3.48) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-164 (16.170.214.206 | 10.0.1.237) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-163 (13.51.48.243 | 10.0.3.179) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-162 (13.50.4.12 | 10.0.2.61) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-161 (16.170.143.172 | 10.0.3.207) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-160 (13.48.67.8 | 10.0.2.123) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-16 (13.49.65.31 | 10.0.2.151) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-159 (13.49.18.27 | 10.0.2.15) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-158 (13.51.235.92 | 10.0.0.98) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-157 (16.171.57.183 | 10.0.3.152) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-156 (13.50.16.68 | 10.0.0.82) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-155 (16.170.159.150 | 10.0.2.26) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-154 (13.49.223.139 | 10.0.3.105) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-153 (13.51.171.152 | 10.0.3.119) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-152 (16.16.63.240 | 10.0.2.49) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-151 (13.49.46.150 | 10.0.2.167) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-150 (13.49.246.56 | 10.0.1.8) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-15 (13.51.167.15 | 10.0.3.151) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-149 (13.48.29.3 | 10.0.3.212) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-148 (13.51.107.39 | 10.0.2.220) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-147 (13.53.126.37 | 10.0.0.236) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-146 (13.53.102.245 | 10.0.1.54) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-145 (13.51.178.168 | 10.0.1.215) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-144 (16.16.57.191 | 10.0.0.214) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-143 (16.170.230.198 | 10.0.1.236) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-142 (16.170.230.193 | 10.0.3.96) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-141 (16.170.223.223 | 10.0.1.14) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-140 (16.170.162.63 | 10.0.2.110) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-14 (13.49.46.216 | 10.0.2.219) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-139 (13.48.177.4 | 10.0.2.130) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-138 (13.51.69.221 | 10.0.2.238) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-137 (16.170.98.11 | 10.0.0.15) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-136 (13.53.190.23 | 10.0.1.221) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-135 (16.170.172.104 | 10.0.1.113) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-134 (13.50.16.92 | 10.0.0.244) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-133 (13.49.70.153 | 10.0.1.84) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-132 (13.49.80.89 | 10.0.1.67) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-131 (13.51.233.26 | 10.0.1.154) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-130 (16.16.56.167 | 10.0.1.224) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-13 (16.16.56.108 | 10.0.1.189) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-129 (13.48.48.4 | 10.0.2.56) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-128 (16.170.146.79 | 10.0.0.101) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-127 (16.171.60.114 | 10.0.0.72) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-126 (13.51.161.148 | 10.0.0.237) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-125 (13.49.74.143 | 10.0.1.220) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-124 (13.51.47.77 | 10.0.2.177) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-123 (13.49.225.60 | 10.0.1.184) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-122 (16.170.173.163 | 10.0.3.161) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-121 (13.53.207.31 | 10.0.3.53) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-120 (13.51.237.253 | 10.0.1.159) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-12 (13.48.104.128 | 10.0.0.108) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-119 (13.49.70.181 | 10.0.0.71) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-118 (13.50.4.119 | 10.0.1.169) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-117 (13.48.130.185 | 10.0.0.17) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-116 (13.49.223.57 | 10.0.2.200) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-115 (13.51.48.32 | 10.0.3.0) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-114 (13.53.111.218 | 10.0.3.122) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-113 (16.171.47.54 | 10.0.1.18) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-112 (13.51.69.158 | 10.0.2.55) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-111 (13.51.6.106 | 10.0.3.141) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-110 (16.170.143.5 | 10.0.0.208) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-11 (13.49.74.161 | 10.0.2.77) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-109 (13.48.105.194 | 10.0.1.232) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-108 (16.170.157.49 | 10.0.2.239) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-107 (16.171.57.189 | 10.0.3.31) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-106 (13.51.193.187 | 10.0.2.222) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-105 (16.16.64.6 | 10.0.2.250) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-104 (13.51.47.95 | 10.0.3.9) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-103 (13.49.72.83 | 10.0.2.137) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-102 (13.49.223.11 | 10.0.0.206) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-101 (13.49.222.109 | 10.0.2.1) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-100 (13.49.46.117 | 10.0.2.232) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-10 (13.53.182.116 | 10.0.2.187) (shards: -1)
- cluster-scale-test-5-0-db-node-881616f1-1 (16.171.58.237 | 10.0.0.89) (shards: -1)


OS / Image: `ami-0fd6e5fe4a8df0bbb` (aws: eu-north-1)

Test: `scale-180-200-cluster-test-test`
Test id: `881616f1-eda4-4850-a20c-8025d0ffe2f2`
Test name: `scylla-5.0/scale/scale-180-200-cluster-test-test`
Test config file(s):

- [scale-cluster.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/607a2a6dc5a2da1ab2d4d1913bc2549f14d73232/test-cases/scale/scale-cluster.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 881616f1-eda4-4850-a20c-8025d0ffe2f2`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=881616f1-eda4-4850-a20c-8025d0ffe2f2)
- Show all stored logs command: `$ hydra investigate show-logs 881616f1-eda4-4850-a20c-8025d0ffe2f2`

## Logs:
- **db-cluster-881616f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/881616f1-eda4-4850-a20c-8025d0ffe2f2/20220630_125026/db-cluster-881616f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/881616f1-eda4-4850-a20c-8025d0ffe2f2/20220630_125026/db-cluster-881616f1.tar.gz)
- **monitor-set-881616f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/881616f1-eda4-4850-a20c-8025d0ffe2f2/20220630_125026/monitor-set-881616f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/881616f1-eda4-4850-a20c-8025d0ffe2f2/20220630_125026/monitor-set-881616f1.tar.gz)
- **loader-set-881616f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/881616f1-eda4-4850-a20c-8025d0ffe2f2/20220630_125026/loader-set-881616f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/881616f1-eda4-4850-a20c-8025d0ffe2f2/20220630_125026/loader-set-881616f1.tar.gz)
- **sct-runner-881616f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/881616f1-eda4-4850-a20c-8025d0ffe2f2/20220630_125026/sct-runner-881616f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/881616f1-eda4-4850-a20c-8025d0ffe2f2/20220630_125026/sct-runner-881616f1.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/scale/job/scale-180-200-cluster-test-test/3/)

**Comment by fgelcer** [comment]
@yaronkaikov , in today's master status meeting, it was decided what? that a user needs to run the `scylla_io_setup` by his own on any instance type that is not i3 or i4? or it was decided that we need to add `io_properties.yaml` and `io.conf` these other supported instances?

**Comment by yaronkaikov** [comment]
@fgelcer we should add those properties as predefined values for each supported instance type. although i am not sure why, or how

In the mean time, by running `scylla_io_setup` you should overcome this

**Comment by fgelcer** [comment]
@soyacz , based on previous comment by @yaronkaikov , it is similar with the workaround we were trying to do in the upgrade test from OSS

**Comment by fruch** [comment]
@soyacz 

https://github.com/scylladb/scylla-cluster-tests/pull/3631 seems to had a workaround copying the io.conf into place, can we check  why that workaround stopped working ?

**Comment by soyacz** [comment]
> @soyacz
> 
> [scylladb/scylla-cluster-tests#3631](https://github.com/scylladb/scylla-cluster-tests/pull/3631) seems to had a workaround copying the io.conf into place, can we check why that workaround stopped working ?

It fails on Scylla setup - not because of missing files, just because it fails when there are no preconfigured IO settings for this kind of instances (while `is_supported` method returns True for it).

**Comment by fruch** [comment]
> > @soyacz
> > [scylladb/scylla-cluster-tests#3631](https://github.com/scylladb/scylla-cluster-tests/pull/3631) seems to had a workaround copying the io.conf into place, can we check why that workaround stopped working ?
> 
> It fails on Scylla setup - not because of missing files, just because it fails when there are no preconfigured IO settings for this kind of instances (while `is_supported` method returns True for it).

@yaronkaikov  so if it was working in 4.5, this is a regression in SMI, and need to be addressed.

**Comment by yaronkaikov** [comment]
Closed with https://github.com/scylladb/scylla-machine-image/commit/3719904aef157d9df6ca6416613e29469a3261b6
