### ISSUE TITLE
r5 not supported in IO setup, but no clean error shown

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-machine-image#376]
Use any r5 instance in AWS,
use Scylla Enterprise 2022 rc8

upon using the AMI you get:
```
scyllaadm@ip-172-31-31-243:~$ sudo systemctl status scylla-image-setup.service
● scylla-image-setup.service - Scylla Cloud Image Setup service
     Loaded: loaded (/lib/systemd/system/scylla-image-setup.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-07-13 14:40:03 UTC; 11min ago
    Process: 7869 ExecStart=/opt/scylladb/scylla-machine-image/scylla_image_setup (code=exited, status=1/FAILURE)
   Main PID: 7869 (code=exited, status=1/FAILURE)

Jul 13 14:40:03 ip-172-31-31-243 scylla_image_setup[7869]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 42, in <module>
Jul 13 14:40:03 ip-172-31-31-243 scylla_image_setup[7869]:     cloud_instance.io_setup()
Jul 13 14:40:03 ip-172-31-31-243 scylla_image_setup[7869]:   File "/opt/scylladb/scylla-machine-image/lib/scylla_cloud.py", line 689, in io_setup
Jul 13 14:40:03 ip-172-31-31-243 scylla_image_setup[7869]:     return run('/opt/scylladb/scylla-machine-image/scylla_cloud_io_setup', shell=True, check=True)
Jul 13 14:40:03 ip-172-31-31-243 scylla_image_setup[7869]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
Jul 13 14:40:03 ip-172-31-31-243 scylla_image_setup[7869]:     raise CalledProcessError(retcode, process.args,
Jul 13 14:40:03 ip-172-31-31-243 scylla_image_setup[7869]: subprocess.CalledProcessError: Command '/opt/scylladb/scylla-machine-image/scylla_cloud_io_setup' returned non-zero exit status 1.
Jul 13 14:40:03 ip-172-31-31-243 systemd[1]: scylla-image-setup.service: Main process exited, code=exited, status=1/FAILURE
Jul 13 14:40:03 ip-172-31-31-243 systemd[1]: scylla-image-setup.service: Failed with result 'exit-code'.
Jul 13 14:40:03 ip-172-31-31-243 systemd[1]: Failed to start Scylla Cloud Image Setup service.
```

which likely points to missing instance type, but in such case there should be fallback to iotune, which is NOT happening, hence this bug

**Comment by tarzanek** [comment]
crosslinking, since I saw both on same setup: https://github.com/scylladb/scylla-machine-image/issues/375

**Comment by tarzanek** [comment]
@syuu1228 is above a regression of moving the code for io setup outside of scylla?

**Comment by tarzanek** [comment]
or could it be the same as https://github.com/scylladb/scylla-machine-image/issues/370 ? @fruch can you help me decide/route this issue?

**Comment by tarzanek** [comment]
> @tarzanek With 2021.1 it fallback to run io tune ? if yes it's a regression that need to be fixed. 

yes, fallback to iotune was always there

> 
> Otherwise it's need to be discussed with @yaronkaikov  and @syuu1228

**Comment by fruch** [comment]
@yaronkaikov if this is indeed a regression, we need to fix

**Comment by benipeled** [comment]
This is the missing fallback [0] and as you can see it exists on scylla repo (branch 2021.1) but is missing from scylla-machine-image - not sure if it was missed in the scylla -> scylla-machine-image switch or not added on purpose,

In any case the `run_iotune` function should be added to `scylla_cloud_io_setup.py` to support supported-instance without pre-configure io

[0] https://github.com/scylladb/scylla-enterprise/blob/af3da2d7ac8b83e1710c418b269c3c85bd1fdbe4/dist/common/scripts/scylla_io_setup#L374-L378

**Comment by fruch** [comment]
> > This is the missing fallback [0] and as you can see it exists on scylla repo (branch 2021.1) but is missing from scylla-machine-image - not sure if it was missed in the scylla -> scylla-machine-image switch or not added on purpose,
> > In any case the `run_iotune` function should be added to `scylla_cloud_io_setup.py` to support supported-instance without pre-configure io
> > /cc @syuu1228 @tarzanek
> > [0] https://github.com/scylladb/scylla-enterprise/blob/af3da2d7ac8b83e1710c418b269c3c85bd1fdbe4/dist/common/scripts/scylla_io_setup#L374-L378
> 
> Please refer description I posted at [scylladb/scylladb#9828 (comment)](https://github.com/scylladb/scylladb/issues/9828#issuecomment-1153832731), I changed the behavor not to run iotune automatically when pre-configure parameter does not exist.

The reason was it's add 5 min if persistence disk is used, in this case it's just types we mark as supported and never supplied configuration. they were working out of the box in 2021.1, why break the users on it on 2022.1/5.0 ? If we decided to not support a type for some reason, that a different story

**Comment by benipeled** [comment]
> > [](https://github.com/scylladb/scylla-enterprise/blob/af3da2d7ac8b83e1710c418b269c3c85bd1fdbe4/dist/common/scripts/scylla_io_setup#L374-L378)
> 
> Please refer description I posted at [scylladb/scylladb#9828 (comment)](https://github.com/scylladb/scylladb/issues/9828#issuecomment-1153832731), I changed the behavor not to run iotune automatically when pre-configure parameter does not exist.

@syuu1228 thanks for the ref, the following from that comment indeed explains the decision 
> _Why we didn't support running iotune on persistent disk on AWS is, because it may take more than 5-10 minutes, users may not understand why scylla-server.service does not start.
So we decided to add warning message to login prompt and let users to run scylla_io_setup instead._

What about using the scylla_login to notify the user about a background process? similar to the `Scylla is starting...` that rais in some situations, we can use `IO tuning is running in the background, make sure to check scylla status bla bla..`
