### ISSUE TITLE
Update `user_data_format_version` tag in Azure images

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-machine-image#391]
When listing images in Azure, `user_data_format_version` is still set to `2` for recent images. Now we are on version `3`.

**Comment by soyacz** [comment]
also tags are in old format e.g.`ScyllaVersion`. Looks like changes from https://github.com/scylladb/scylla-machine-image/pull/383 are not used in Azure

**Comment by fruch** [comment]
> also tags are in old format e.g.`ScyllaVersion`. Looks like changes from #383 are not used in Azure

the images you're seeing there ? from which branch there were created ?

**Comment by soyacz** [comment]
from `master`. Example image tags:
```
ScyllaDB-2022.1.1-0.20220807.e1e2c3d21-1-build-21 {'ScyllaJMXVersion': '2022.1.1-0.20220807.e1e2c3d21-1', 'ScyllaMachineImageVersion': '2022.1.1-20220808.8f63c22-1', 'ScyllaPython3Version': '2022.1.1-0.20220807.e1e2c3d21-1', 'ScyllaToolsVersion': '2022.1.1-0.20220807.e1e2c3d21-1', 'ScyllaVersion': '2022.1.1-0.20220807.e1e2c3d21-1', 'arch': 'x86_64', 'branch': 'master', 'build_id': '21', 'build_tag': '', 'operating_system': 'ubuntu20.04', 'scylla_build_sha_id': '', 'user_data_format_version': '2'}
ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28 {'ScyllaJMXVersion': '5.0.2-0.20220807.299122e78-1', 'ScyllaMachineImageVersion': '5.0.2-20220807.1b1f0b86367-1', 'ScyllaPython3Version': '5.0.2-0.20220807.299122e78-1', 'ScyllaToolsVersion': '5.0.2-0.20220807.299122e78-1', 'ScyllaVersion': '5.0.2-0.20220807.299122e78-1', 'arch': 'x86_64', 'branch': 'master', 'build_id': '28', 'build_tag': '', 'operating_system': 'ubuntu20.04', 'scylla_build_sha_id': '', 'user_data_format_version': '2'}
```
btw. they're quite old (07.08)

**Comment by fruch** [comment]
branches ScyllaDB-2022.1 and 5.0, probably doesn't hold the fixes you were referring too, of consolidating the tags

i.e. the one you are showing here, are not from master, but from release branches ! (explains why they are old, they get promoted only once in a while)

them having `'branch': 'master'` is probably the problem, they should be altered

@yaronkaikov you think the tagging consolidation can be back ported ? to at least fix make a fix to the branches to put the correct branches ?

**Comment by soyacz** [comment]
Ok, I've found them. I just don't see due to build_id being a date and not an integer:
```
scylla-5.2.0-dev-x86_64-2022-08-18T12-36-31Z {'arch': 'x86_64', 'branch': 'master', 'build_id': '2022-08-18T12-36-24', 'build_tag': 'jenkins-scylla-master-azure-image-217', 'operating_system': 'ubuntu20.04', 'scylla_build_sha_id': '99cff22f18b81e899d64af4639417e4ef20563bf', 'scylla_jmx_version': '5.2.0~dev-0.20220818.055340ae39ba-1', 'scylla_machine_image_version': '5.2.0~dev-20220818.388dad1f3a7-1', 'scylla_python3_version': '5.2.0~dev-0.20220818.055340ae39ba-1', 'scylla_tools_version': '5.2.0~dev-0.20220818.055340ae39ba-1', 'scylla_version': '5.2.0~dev-0.20220818.055340ae39ba-1', 'user_data_format_version': '3'}
scylla-5.2.0-dev-x86_64-2022-08-22T04-18-36Z {'arch': 'x86_64', 'branch': 'master', 'build_id': '2022-08-22T04-18-26', 'build_tag': 'jenkins-scylla-master-azure-image-218', 'operating_system': 'ubuntu20.04', 'scylla_build_sha_id': '4c66b02f12d1bb1ae1903aa192e269c3a4351112', 'scylla_jmx_version': '5.2.0~dev-0.20220822.fa7033bc2be5-1', 'scylla_machine_image_version': '5.2.0~dev-20220822.388dad1f3a7-1', 'scylla_python3_version': '5.2.0~dev-0.20220822.fa7033bc2be5-1', 'scylla_tools_version': '5.2.0~dev-0.20220822.fa7033bc2be5-1', 'scylla_version': '5.2.0~dev-0.20220822.fa7033bc2be5-1', 'user_data_format_version': '3'}
```
@yaronkaikov is it a new standard to put date into `build_id`?

**Comment by yaronkaikov** [comment]
> Ok, I've found them. I just don't see due to build_id being a date and not an integer:
> 
> ```
> scylla-5.2.0-dev-x86_64-2022-08-18T12-36-31Z {'arch': 'x86_64', 'branch': 'master', 'build_id': '2022-08-18T12-36-24', 'build_tag': 'jenkins-scylla-master-azure-image-217', 'operating_system': 'ubuntu20.04', 'scylla_build_sha_id': '99cff22f18b81e899d64af4639417e4ef20563bf', 'scylla_jmx_version': '5.2.0~dev-0.20220818.055340ae39ba-1', 'scylla_machine_image_version': '5.2.0~dev-20220818.388dad1f3a7-1', 'scylla_python3_version': '5.2.0~dev-0.20220818.055340ae39ba-1', 'scylla_tools_version': '5.2.0~dev-0.20220818.055340ae39ba-1', 'scylla_version': '5.2.0~dev-0.20220818.055340ae39ba-1', 'user_data_format_version': '3'}
> scylla-5.2.0-dev-x86_64-2022-08-22T04-18-36Z {'arch': 'x86_64', 'branch': 'master', 'build_id': '2022-08-22T04-18-26', 'build_tag': 'jenkins-scylla-master-azure-image-218', 'operating_system': 'ubuntu20.04', 'scylla_build_sha_id': '4c66b02f12d1bb1ae1903aa192e269c3a4351112', 'scylla_jmx_version': '5.2.0~dev-0.20220822.fa7033bc2be5-1', 'scylla_machine_image_version': '5.2.0~dev-20220822.388dad1f3a7-1', 'scylla_python3_version': '5.2.0~dev-0.20220822.fa7033bc2be5-1', 'scylla_tools_version': '5.2.0~dev-0.20220822.fa7033bc2be5-1', 'scylla_version': '5.2.0~dev-0.20220822.fa7033bc2be5-1', 'user_data_format_version': '3'}
> ```
> 
> @yaronkaikov is it a new standard to put date into `build_id`?

@soyacz The value of `build_id` is taken from jenkins environment variable `env.BUILD_ID` which according to the documentation should be the build number. not sure why it's a date. will look into it

**Comment by yaronkaikov** [comment]
> branches ScyllaDB-2022.1 and 5.0, probably doesn't hold the fixes you were referring too, of consolidating the tags
> 
> i.e. the one you are showing here, are not from master, but from release branches ! (explains why they are old, they get promoted only once in a while)
> 
> them having `'branch': 'master'` is probably the problem, they should be altered
> 
> @yaronkaikov you think the tagging consolidation can be back ported ? to at least fix make a fix to the branches to put the correct branches ?
I will do the backports later

**Comment by yaronkaikov** [comment]
@fruch Backport done to 5.0 2022.1 5.1 and 2022.2
