### ISSUE TITLE
Preinstalled Scylla image has outdated packages after upgrade

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-machine-image#399]
When upgrading Scylla on preinstalled Scylla images, after upgrade we can see outdated packages. Example for upgrade from 5.0.3 to recent dev:
```
scyllaadm@rolling-upgrade--centos-db-node-30b489f7-2:~$ sudo apt list --upgradable
Listing... Done
intel-microcode/focal-updates,focal-security 3.20220809.0ubuntu0.20.04.1 amd64 [upgradable from: 3.20220510.0ubuntu0.20.04.1]
scylla-machine-image/stable,stable 5.2.0~dev-20220914.04dc4b22edd-1 all [upgradable from: 5.0.3-20220908.86777998fad-1]
vim-common/focal-updates,focal-security 2:8.1.2269-1ubuntu5.8 all [upgradable from: 2:8.1.2269-1ubuntu5.7]
vim-runtime/focal-updates,focal-security 2:8.1.2269-1ubuntu5.8 all [upgradable from: 2:8.1.2269-1ubuntu5.7]
vim-tiny/focal-updates,focal-security 2:8.1.2269-1ubuntu5.8 amd64 [upgradable from: 2:8.1.2269-1ubuntu5.7]
vim/focal-updates,focal-security 2:8.1.2269-1ubuntu5.8 amd64 [upgradable from: 2:8.1.2269-1ubuntu5.7]
xxd/focal-updates,focal-security 2:8.1.2269-1ubuntu5.8 amd64 [upgradable from: 2:8.1.2269-1ubuntu5.7]
```
When upgrade starts from older version (e.g. 4.6) we can see even older packages.
It looks upgrading with use of scylla-packages file is not upgrading all the packages. Thus upgraded VM != VM from image.

This is an issue as we don't extensively test Scylla with older packages like this.

Also what I can see from above listing, `scylla-machine-image` is also not upgraded when using `scylla-packages` file.

**Comment by fruch** [comment]
I would argue there no much use for scylla machine image after the first boot of an instance.

Maybe if we ever want to upgrade the login "motd" and such.

**Comment by soyacz** [comment]
> I would argue there no much use for scylla machine image after the first boot of an instance.
> 
> Maybe if we ever want to upgrade the login "motd" and such.

Maybe we don't care about this one, but package like `intel-microcode` is important. It looks this packages file is not created properly. So upgrade of AMI does not result in the same packages like in VM created from version we upgrade to.

**Comment by fruch** [comment]
@soyacz the packages you are referring to, are not directly depended by any of scylla packages, if they are import enough for scylla they should be on it's dependency graph. 

https://github.com/scylladb/scylla-machine-image/blob/e7e7daa0ced4d650013849711d7ced5ebb6ed569/packer/scylla_install_image#L224

I don't think it's a real issue, with one exception we might need to be more explicit about, is the kernel.

**Comment by soyacz** [comment]
I opened this discussion to resolve my concern: should upgraded image contain the same list of packages as in VM created from upgraded version?

I was thinking that the whole idea of `scylla-packages` file was about that.  Otherwise, we don't need this file at all - apt can resolve dependencies by itself without this file.

**Comment by fruch** [comment]
> I opened this discussion to resolve my concern: should upgraded image contain the same list of packages as in VM created from upgraded version?
> 
> I was thinking that the whole idea of `scylla-packages` file was about that.  Otherwise, we don't need this file at all - apt can resolve dependencies by itself without this file.
> 

Again I don't know who initiated this whole change to the upgrade docs, and for what reasons... I don't really fully understand what the idea here...

**Comment by mykaul** [comment]
> > I would argue there no much use for scylla machine image after the first boot of an instance.
> > Maybe if we ever want to upgrade the login "motd" and such.
> 
> Maybe we don't care about this one, but package like `intel-microcode` is important. It looks this packages file is not created properly. So upgrade of AMI does not result in the same packages like in VM created from version we upgrade to.

intel-microcode is not important for a VM on AWS, to the best of my knowledge.

**Comment by soyacz** [comment]
@mykaul `scylla-packages` file was not filled properly, but anyway I think we drop this approach anyway as specific versions can't be installed after newer one appears in Ubuntu repositories. @yaronkaikov please correct me if I'm wrong. Possibly this bug can be closed.
