### ISSUE TITLE
Python2.7 not present by default on latest 5.2 AMIs

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-machine-image#401]
[Run 1](http://argus.scylladb.com/test/a2b90d5a-c79b-4f9d-a9a7-98974e88c866/runs?additionalRuns%5B%5D=7d2fbbef-09e3-4e98-985f-2e1b3970a07c) | [Run 2](http://argus.scylladb.com/test/3b2cc0be-cb4d-44eb-8329-0309c6207e4f/runs?additionalRuns%5B%5D=7913d8ee-8ee2-45ba-af1a-14d4b4c4354d)

Pretty much every nemesis here that uses cqlsh failed with "No appropriate python interpreter found", because python2.7 is not installed in the AMI used. Since cqlsh requires that version specifically, it doesn't work.

AMI ids: `ami-012bc92fd5fad9502`, `ami-012bc92fd5fad9502` (region: `eu-north-1`)

Using said AMIs manually to see if python2.7 binary is installed:
```
scyllaadm@ip-172-31-10-128:~$ whereis python
python: /usr/bin/python3.8 /usr/lib/python3.9 /usr/lib/python3.8 /usr/lib/python2.7 /etc/python3.8 /usr/local/lib/python3.8
```
and trying to run cqlsh directly we get:
```
scyllaadm@ip-172-31-10-128:~$ cqlsh
No appropriate python interpreter found.
```

```
2022-09-09 04:13:31.256: (DisruptionEvent Severity.ERROR) period_type=end event_id=093c5295-5408-4866-8708-340726253f1b duration=2s: nemesis_name=ToggleTableIcs target_node=Node longevity-tls-50gb-3d-master-db-node-7d2fbbef-2 [16.16.28.220 | 10.0.0.116] (seed: False) errors=Encountered a bad command exit code!
Command: 'cqlsh --no-color -u cassandra -p \'cassandra\'  --request-timeout=120 --connect-timeout=60 --ssl -e "SELECT keyspace_name, table_name, compaction FROM system_schema.tables" 10.0.0.116 9042'
Exit code: 1
Stdout:
Stderr:
No appropriate python interpreter found.
```

**Comment by fruch** [comment]
It was noticed already see: https://github.com/scylladb/scylla-pkg/issues/3094

the change cause it was yanked out, can you check the jobs failing for you with latest master versions ?

**Comment by roydahan** [comment]
I think it's solved already.

**Comment by k0machi** [comment]
> It was noticed already see: [scylladb/scylla-pkg#3094](https://github.com/scylladb/scylla-pkg/issues/3094)
> 
> the change cause it was yanked out, can you check the jobs failing for you with latest master versions ?

Latest master is fine, so good on that front
