### ISSUE TITLE
Latest release image tag (5.1) violates semantic versioning

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-machine-image#406]
Latest release of the docker scylla image is `5.1`, which violates the `semantic versioning` structure.
It must have been `5.1.0`.
`Scylla-operator` doesn't work correctly with `non`-`semver`-like docker tags.

![Screenshot from 2022-10-25 17-51-13](https://user-images.githubusercontent.com/3796058/197807773-528d100b-21b2-4851-a8b3-550e3147a67f.png)

Old similar issue for reference: https://github.com/scylladb/scylladb/issues/9543

**Comment by fruch** [comment]
@vponomaryov move this to scylla-pkg

This repo doesn't have the code that handles the building of the docker images.

**Comment by vponomaryov** [comment]
> @vponomaryov move this to scylla-pkg
> 
> This repo doesn't have the code that handles the building of the docker images.

Done: https://github.com/scylladb/scylla-pkg/issues/3137
