### ISSUE TITLE
Azure - use /dev/sdb for swap, core dump, etc.

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-machine-image#420]
From https://learn.microsoft.com/en-us/azure/virtual-machines/lasv3-series :
```
Temp disk: Lasv3-series VMs have a standard SCSI-based temp resource disk for use by the OS paging or swap file (D: on Windows, /dev/sdb on Linux). This disk provides 80 GiB of storage, 4000 IOPS, and 80 MBps transfer rate for every 8 vCPUs. For example, Standard_L80as_v3 provides 800 GiB at 40000 IOPS and 800 MBPS. This configuration ensures that the NVMe drives can be fully dedicated to application use. This disk is ephemeral, and all data is lost on stop or deallocation.
```

**Comment by syuu1228** [comment]
@yaronkaikov I cannot launch instance on Lasv3-series, it says "Insufficient quota - family limit":
![Screenshot from 2023-01-23 20-54-57](https://user-images.githubusercontent.com/183648/214033949-7077b950-7ae4-4089-ac76-15c198cc5924.png)
Can we increase quotas?

**Comment by yaronkaikov** [comment]
@syuu1228 Sorry looks like i missed this one, will check it
