### ISSUE TITLE
Move to Ubuntu 22.04.2 release

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-machine-image#438]
I'm not even sure if it's not what we'll get anyway when we rebuild our images.

1. Unsure if for 5.2 - I don't think so.
2. Unsure if we should adopt the 5.19 kernel, or stick to the 5.15 one.

See https://www.omgubuntu.co.uk/2023/02/ubuntu-22-04-2-download for details.

**Comment by yaronkaikov** [comment]
@mykaul We are already using it. This is from the latest AMI image:
```
scyllaadm@ip-10-0-4-123:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by yaronkaikov** [comment]
and kernel version is:
```
scyllaadm@ip-10-0-4-123:~$ uname -r
5.15.0-1030-aws
```

**Comment by mykaul** [comment]
Nice, as it was only released last week or so.
It also has some changes we've already made - https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/1981109 for example ('server image pulls in ModemManager via fwupd, consumes 25MiB RAM in every container' )

**Comment by benipeled** [comment]
@yaronkaikov this is due to the dedicated logic we have for **AMI** on scylla.json to get the latest ubuntu image,
Make sure it's the same case on azure, gce

PS> I'm not sure it should work this way since it replaces the base image under the hood - although it's patch version only - it can cause bugs that may take time to find the root cause (version change)

**Comment by mykaul** [comment]
> PS> I'm not sure it should work this way since it replaces the base image under the hood - although it's patch version only - it can cause bugs that may take time to find the root cause (version change)

which is why I wasn't sure it should go to 5.2. Otherwise, we should strive to be on the latest enterprise LTS release.
