### ISSUE TITLE
[GCP image]: use 22.04 lts kernel version during build

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-machine-image#452]
Similar to the work we did for AWS https://github.com/scylladb/scylla-machine-image/pull/443 we should do the same for GCP. 

Currently the lts kernel for 22.04 is under testing https://www.google.com/url?q=https://ubuntu.pkgs.org/22.04/ubuntu-proposed-main-amd64/linux-gcp-lts-22.04_5.15.0.1034.30_amd64.deb.html&sa=D&source=docs&ust=1683796254685453&usg=AOvVaw20cpSUX5u3QK15SZyDKTrZ .

**Comment by DoronArazii** [comment]
> /cc @DoronArazii @mykaul

Thanks Yaron.
It's being tracked on the daily release status page under 2023.1.0
