### ISSUE TITLE
scylla_coredump_setup should be called with --compress to enable zstd compression of the core dumps

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-machine-image#462]
Need to verify, but if Ubuntu 22.2 LTS systemd is compiled with zstd as default compression, we must configure the coredump to be compressed.
This will reduce significantly the time it takes to write the coredump, to transfer it, etc.
Example:
```
ykaul@ykaul Downloads]$ file ip-172-18-2-215
ip-172-18-2-215: ELF 64-bit LSB core file, x86-64, version 1 (SYSV), SVR4-style, from '/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --', real uid: 114, effective uid: 114, real gid: 120, effective gid: 120, execfn: '/opt/scylladb/libexec/scylla', platform: 'x86_64'
[ykaul@ykaul Downloads]$ du -ch ip-172-18-2-215
14G	ip-172-18-2-215
14G	total
[ykaul@ykaul Downloads]$ time zstd ip-172-18-2-215
ip-172-18-2-215      : 11.17%   (  13.8 GiB =>   1.55 GiB, ip-172-18-2-215.zst)
real	0m19.028s
user	0m20.921s
sys	0m3.490s
[ykaul@ykaul Downloads]$ du -ch ip-172-18-2-215.zst
1.6G	ip-172-18-2-215.zst
1.6G	total
```

I had an ever more drastic example of 111GB compressed by 90% reduction of size.

**Comment by mykaul** [comment]
Example for benefit (not only faster, but takes far less space) - see https://github.com/scylladb/scylla-cluster-tests/issues/7234#issuecomment-2094757695

**Comment by syuu1228** [comment]
Sent patch to enable compress by default when ZSTD detected:
https://github.com/scylladb/scylladb/pull/18854

Implemented it on scylla_coredump_setup not machine-image script, since this looks like generic issue not just machine-image.

**Comment by yaronkaikov** [comment]
@syuu1228 Can this be closed? i saw that the PR was promoted

**Comment by fruch** [comment]
and this is breaking artifacts jobs
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu2204-test/576/

**Comment by mykaul** [comment]
> and this is breaking artifacts jobs https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu2204-test/576/

@yaronkaikov - please revert.

**Comment by yaronkaikov** [comment]
> > and this is breaking artifacts jobs https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu2204-test/576/
> 
> @yaronkaikov - please revert.

I can't revert, it's in Scylla core https://github.com/scylladb/scylladb/pull/18854

**Comment by yaronkaikov** [comment]
@mykaul , @syuu1228 is working on a fix now, so i expect it to be ready today (hopefully) 

@syuu1228 please update

**Comment by syuu1228** [comment]
Closing, since the patch is merged https://github.com/scylladb/scylladb/commit/cbf33aba5c915c0c96c3f382819e3a1db57651eb
