### ISSUE TITLE
Upgrade AMI base image to Ubunto LTS 22.04.3

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-machine-image#468]
See https://lists.ubuntu.com/archives/ubuntu-announce/2023-August/000294.html

**Comment by benipeled** [comment]
(Unfortunately) we always build with the latest image as you can see the packer filter

https://github.com/scylladb/scylla-machine-image/blob/23eefa47371b97e2c38aa83ea49cafb0204744c7/packer/scylla.json#L56-L62

based on the param from build_image.sh
https://github.com/scylladb/scylla-machine-image/blob/23eefa47371b97e2c38aa83ea49cafb0204744c7/packer/build_image.sh#L263-L282

**Comment by benipeled** [comment]
So the latest AMI is built with 22.04.3

```
scyllaadm@ip-10-0-1-188:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by mykaul** [comment]
Thanks - I think this needs to be controlled. I'm happy to see it, but there's also risk associated with such change.

**Comment by benipeled** [comment]
> Thanks - I think this needs to be controlled. I'm happy to see it, but there's also risk associated with such change.

Agree,
We discussed it a few times on different forums and since it's only for minor releases (the major version is hardcoded) we got no clear decision about it
