### ISSUE TITLE
scylla-image-setup service is started when stopping the source instance

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-machine-image#49]
#### Description

I found scylla-image-setup service was started when stopping the source instance.
It should be unexpected, and it's interrupted during coredump setup.

When new instance is created, another scylla-image-setup will be executed. It will overwrite some change of first scylla-image-setup.

The problem was found in master AMI: scylla_2020-08-03T23-11-29Z (ami-05b55eb1eb02c4a3a)
I also reproduced with my AMI (us-east-1: ami-0005610b660b7d0b0)

#### New instance system log: (include system log of creating AMI)

[log-from-begin.txt](https://github.com/scylladb/scylla-machine-image/files/5029239/log-from-begin.txt)
[ami-build-log.txt](https://github.com/scylladb/scylla-machine-image/files/5029243/ami-build-log.txt)

#### AMI build log:

- the source instance was stopped around 13:36:57

```
2020/08/05 13:36:57 [INFO] (telemetry) ending shell
2020/08/05 13:36:57 ui: ESC[1;32m==> amazon-ebs: Stopping the source instance...ESC[0m
2020/08/05 13:36:57 ui: ESC[0;32m    amazon-ebs: Stopping instanceESC[0m
2020/08/05 13:36:58 ui: ESC[1;32m==> amazon-ebs: Waiting for the instance to stop...ESC[0m
2020/08/05 13:37:14 ui: ESC[1;32m==> amazon-ebs: Enabling Enhanced Networking (SR-IOV)...ESC[0m
2020/08/05 13:37:15 ui: ESC[1;32m==> amazon-ebs: Enabling Enhanced Networking (ENA)...ESC[0m
2020/08/05 13:37:16 ui: ESC[1;32m==> amazon-ebs: Creating AMI scylla_2020-08-05T13-33-11Z from instance i-0aace976ce6ef80d6ESC[0m
2020/08/05 13:37:17 ui: ESC[0;32m    amazon-ebs: AMI: ami-0005610b660b7d0b0ESC[0m
2020/08/05 13:37:17 ui: ESC[1;32m==> amazon-ebs: Waiting for AMI to become ready...ESC[0m
2020/08/05 13:43:52 ui: ESC[1;32m==> amazon-ebs: Modifying attributes on AMI (ami-0005610b660b7d0b0)...ESC[0m
```

#### uptime of new instance
```
[scyllaadm@ip-10-99-0-244 ~]$ uptime -s
2020-08-05 13:49:17
```

#### System log of new instance

- scylla-image-setup service was started in stopping source instance
- it's after :
    - basic scylla_setup
        - `scylla_setup --ntp-domain amazon --no-coredump-setup --no-sysconfig-setup --no-raid-setup --no-io-setup --no-bootparam-setup --no-ec2-check --no-swap-setup`
        - scylla.slice was created and started
    - `sudo amazon-linux-extras install kernel-ng`
    - cloud.cfg update

```
[scyllaadm@ip-10-99-0-244 ~]$ sudo journalctl  -S '2020-08-05 13:30:00' |less

Aug 05 13:33:39 ip-172-30-0-169 systemd[1]: Starting Network.

<install scylla>
<install scylla-machine-image, scylla-debuginfo>
</opt/scylladb/scripts/scylla_setup --ntp-domain amazon --no-coredump-setup --no-sysconfig-setup --no-raid-setup --no-io-setup --no-bootparam-setup --no-ec2-check --no-swap-setup>

Aug 05 13:36:33 ip-172-30-0-169.ec2.internal systemd[1]: Created slice scylla.slice.
Aug 05 13:36:33 ip-172-30-0-169.ec2.internal systemd[1]: Starting scylla.slice.

<sudo amazon-linux-extras install kernel-ng>

2020/08/05 13:36:33 ui: ESC[0;32m    amazon-ebs: ESC[1;31mNo swap is configured, it is highly recommended to setup swap on Scylla node.ESC[0mESC[0m
2020/08/05 13:36:33 ui: ESC[0;32m    amazon-ebs: ScyllaDB setup finished.ESC[0m

Aug 05 13:36:56 ip-172-30-0-169.ec2.internal systemd[1]: Stopping Dynamically Generate Message Of The Day...
Aug 05 13:36:56 ip-172-30-0-169.ec2.internal systemd[1]: Starting Dynamically Generate Message Of The Day...
Aug 05 13:36:56 ip-172-30-0-169.ec2.internal systemd[1]: Created slice Slice used to run Scylla. Maximum priority for IO and CPU.
Aug 05 13:36:56 ip-172-30-0-169.ec2.internal systemd[1]: Starting Slice used to run Scylla. Maximum priority for IO and CPU.
Aug 05 13:36:56 ip-172-30-0-169.ec2.internal systemd[1]: Starting Scylla Cloud Image Setup service...
...
<scylla-image-setup was interruptted during coredump setup>

Aug 05 13:36:58 ip-172-30-0-169.ec2.internal systemd[1]: Stopped target Cloud-init target.
Aug 05 13:36:58 ip-172-30-0-169.ec2.internal sshd[3679]: Received signal 15; terminating.
Aug 05 13:36:58 ip-172-30-0-169.ec2.internal systemd[1]: Stopping Cloud-init target.
Aug 05 13:36:58 ip-172-30-0-169.ec2.internal systemd[1]: Stopped Scylla Cloud Image Setup service.

...
<scylla-image-setup during new instance init>
Aug 05 13:49:32 ip-172-30-0-169.ec2.internal systemd[1]: Starting Scylla Cloud Image Setup service...

Aug 05 13:50:25 ip-10-99-0-244.ec2.internal scylla_image_setup[3574]: 4+0 records in
Aug 05 13:50:25 ip-10-99-0-244.ec2.internal scylla_image_setup[3574]: 4+0 records out
Aug 05 13:50:25 ip-10-99-0-244.ec2.internal scylla_image_setup[3574]: 4294967296 bytes (4.3 GB) copied, 32.5004 s, 132 MB/s
Aug 05 13:50:39 ip-10-99-0-244.ec2.internal dhclient[3529]: XMT: Solicit on eth0, interval 64950ms.
Aug 05 13:51:14 ip-10-99-0-244.ec2.internal scylla_image_setup[3574]: Setting up swapspace version 1, size = 4 GiB (4294963200 bytes)
Aug 05 13:51:14 ip-10-99-0-244.ec2.internal scylla_image_setup[3574]: no label, UUID=bc86a46c-5b41-4987-b492-dbe0353bbfce
```

**Comment by amoskong** [comment]
This issue can be workarounded by moving enable of scylla-image-setup.service to the end.
But I saw scylla-server is starting during stopping source instance, need to find the root reason.

```
diff --git a/aws/ami/files/scylla_install_ami b/aws/ami/files/scylla_install_ami
index 8b16dcb..78e917b 100755
--- a/aws/ami/files/scylla_install_ami
+++ b/aws/ami/files/scylla_install_ami
@@ -76,8 +76,6 @@ if __name__ == '__main__':
     if args.repo_for_update:
         run('curl -L -o /etc/yum.repos.d/scylla.repo {REPO_FOR_UPDATE}'.format(REPO_FOR_UPDATE=args.repo_for_update))
 
-    run('systemctl daemon-reload')
-    run('systemctl enable scylla-image-setup.service')
     with open('/etc/cloud/cloud.cfg') as f:
         lines = f.readlines()
     with open('/etc/cloud/cloud.cfg', 'w') as f:
@@ -99,3 +97,5 @@ if __name__ == '__main__':
     with open('/etc/cloud/cloud.cfg', 'w') as f:
         f.write(cfg2)
     shutil.move('{}/99_user_alias.cfg'.format(homedir), '/etc/cloud/cloud.cfg.d')
+    run('systemctl daemon-reload')
+    run('systemctl enable scylla-image-setup.service')
```

**Comment by amoskong** [comment]
Hi @slivne 

Currently node_exporter.service will be enabled and started during scylla_setup, is it expected?
it should be fine to start node_exporter after restart.

I tried to disable start of node_exporter.service in scylla_setup (node_exporter_install), the scylla-server can still be started during stopping source instance.

----
I saw the scylla-image-setup.service or scylla-server.service is **always** started after created and started `scylla.slice`.
I didn't find a way to disable this.

```
Aug 06 01:40:06 ip-172-30-0-92.ec2.internal systemd[1]: Created slice scylla.slice.
Aug 06 01:40:06 ip-172-30-0-92.ec2.internal systemd[1]: Starting scylla.slice.
Aug 06 01:40:06 ip-172-30-0-92.ec2.internal systemd[1]: Created slice Slice used to run Scylla. Maximum priority for IO and CPU.
Aug 06 01:40:06 ip-172-30-0-92.ec2.internal systemd[1]: Starting Slice used to run Scylla. Maximum priority for IO and CPU.
Aug 06 01:40:06 ip-172-30-0-92.ec2.internal systemd[1]: Starting Scylla Server...
Aug 06 01:40:06 ip-172-30-0-92.ec2.internal systemd[1]: Created slice Slice used to run companion programs to Scylla. Memory, CPU and IO restricted.
Aug 06 01:40:06 ip-172-30-0-92.ec2.internal systemd[1]: Starting Slice used to run companion programs to Scylla. Memory, CPU and IO restricted.
```

**Comment by fruch** [comment]
@amoskong It's not clear to me what's the bug here ? what are the changes the are overwritten ? how does it manifest before swap configuration was enabled ?

**Comment by amoskong** [comment]
> @amoskong It's not clear to me what's the bug here ? what are the changes the are overwritten ? how does it manifest before swap configuration was enabled ?

We don't expect scylla-image-setup service is started in creating AMI, right? we expect it firstly starts when the new instance is creating /initing.

**Comment by fruch** [comment]
Up until the swap issue, we didn't really cared if it was started during the stop of the instance or not.
the logic on instance boot wasn't related to that fact.

If there still a real issue with this happening ? if not, I don't see a point in chasing this issue.

**Comment by amoskong** [comment]
> Up until the swap issue, we didn't really cared if it was started during the stop of the instance or not.
> the logic on instance boot wasn't related to that fact.
> 
> If there still a real issue with this happening ? if not, I don't see a point in chasing this issue.

In my tests, the scylla-ami-setup service will be interrupted after coredump setup, swap setup isn't really executed.

The curious question is why it's started after enable?

**Comment by fruch** [comment]
I think we found the root cause this issue, it's `scylla-fstrim.timer` that spin up scylla-server in all kind of cases.
we seen it as part of the scylla-cloud installations, that any systemd services that `Wants` timers, would kick this dependency again

**Comment by yaronkaikov** [comment]
@fruch Any idea if it's relevant ? 4.3 is long gone

**Comment by fruch** [comment]
The root cause was the fstrim.timer, and we are not using it anymore on master.
