### ISSUE TITLE
Move swapfile to data volume (/var/lib/scylla)

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla-machine-image#492]
Related with #491, we want to reduce the image size, but if we do that we will not have enough disk space for swapfile.
To fix the problem, we need to move swapfile to the data volume (/var/lib/scylla) to avoid running out disk space of rootfs.

see: https://github.com/scylladb/scylla-machine-image/pull/491#issuecomment-1842737739

**Comment by fruch** [comment]
> It's not a good idea, wasting fast+expensive NVMe space.
> 
> Maybe we can add an EBS volume to the AMI.

bard is nice

but, the issue is that now you need to teach whom is using the image, that he need todo something else 
to get swap as we recommend 

the whole reason it was done in build time, was to save time and complexity for cloud deployment
the price for it was bigger AMIs.

we can't take a step back, without syncing it with whom is depending on it.

**Comment by avikivity** [comment]
Bard:

To create an AMI that creates a new EBS volume and attaches to it, you can use a combination of user data and cloud-init to automate the process. Here's a general outline of the steps involved:

1. **Create a script to create the EBS volume and attach it to the instance:** Write a script that uses the AWS CLI or boto3 library to create a new EBS volume of the desired size and attach it to the instance. This script should be placed in the user data section of the instance configuration.

2. **Create an AMI from the instance:** Once the script has successfully created and attached the EBS volume, create an AMI from the instance. This AMI will capture the state of the instance, including the attached EBS volume.

3. **Launch new instances from the AMI:** When you launch new instances from the AMI, the EBS volume will be automatically attached to each instance. This ensures that each instance has the same storage capacity and configuration.

Here's an example of a user data script that uses the AWS CLI to create a new EBS volume of 100GB and attach it to the instance:


#!/bin/bash

# Set the AWS region
aws_region=us-east-1

# Create a new EBS volume of 100GB
aws ec2 create-volume --volume-type gp2 --size 100 --region $aws_region > volume.json

# Extract the volume ID from the JSON output
volume_id=$(cat volume.json | jq -r '.VolumeId')

# Attach the EBS volume to the instance
aws ec2 attach-volume --instance-id $(curl -s http://169.254.169.254/latest/meta-data/instance-id) --volume-id $volume_id --region $aws_region

# Format and mount the EBS volume
mkfs.ext4 /dev/xvdf
mount /dev/xvdf /mnt/ebs


To create an AMI from the instance, you can use the AWS CLI or the Amazon EC2 console. Once the AMI is created, you can launch new instances from it and the EBS volume will be automatically attached to each instance.

**Comment by avikivity** [comment]
I think bard is crap

**Comment by avikivity** [comment]
but, we can certainly create a swap volume in cloud-init on the first boot.

**Comment by avikivity** [comment]
Why does the root disk need to change?

**Comment by fruch** [comment]
> We can add additional EBS volume with following change on packer configuration file:
> ```
> diff --git a/packer/scylla.json b/packer/scylla.json
> index f06cc7c..012e4b1 100644
> --- a/packer/scylla.json
> +++ b/packer/scylla.json
> @@ -36,6 +36,12 @@
>          {
>            "device_name": "/dev/sdi",
>            "virtual_name": "ephemeral7"
> +        },
> +        {
> +          "device_name": "/dev/sdj",
> +          "volume_type": "gp3",
> +          "volume_size": 20,
> +          "delete_on_termination": "true"
>          }
>        ],
>        "ami_name": "{{user `image_name`| clean_resource_name}}",
> ```
> With the configuration file, machine-image will have additional disk by default.
> However, I haven't find a way to do same on GCE.
> Maybe user have to manually attach additional disk.

How is it different from sizing the root disk ? both would be saved and we go back to the sizing, but you'll have two snapshots ? or I'm missing something

**Comment by yaronkaikov** [comment]
I don't understand why we should calculate the swap based on any disk size. Based on https://github.com/scylladb/scylla-machine-image/commit/069318bb48963aa5bede707579e499a8bd1288c4 , there is a simple calculation to the relevant size of the swap, the max value should be 16Gb, how long does it take to create it during first boot as @avikivity suggested?

**Comment by syuu1228** [comment]
Closing, since using the data volume for swap seems not good idea, as @avikivity commented on the thread.
