### ISSUE TITLE
Bundle cqlsh with support for "DESC SCHEMA WITH INTERNALS"

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-machine-image#528]
The latest back/restore procedure is built on a new "DESC SCHEMA WITH INTERNALS" and requires support in CQLSh.
We need to bundle the latest CQLSh with Scylla Image to use it.

https://github.com/scylladb/scylladb/pull/18953

**Comment by tzach** [comment]
@yaronkaikov please prio this feature.

**Comment by fruch** [comment]
@tzach this issue should go on scylladb main repo, when the cqlsh is a submodule

machine image, doesn't control the content...

**Comment by tzach** [comment]
https://github.com/scylladb/scylladb/issues/18989
