### ISSUE TITLE
consider `start_scylla_on_first_boot` to be able to handle strings

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-machine-image#53]
while working with scylla-cloud team,
seem like by mistake they were pass the following in the user-data:
```
"start_scylla_on_first_boot":"false"
```
it consider at true, and did exactly the opposite from what intended.

we should consider supporting also strings for this specific parameter

and also to print clearly the user-data we are getting for debug

**Comment by fruch** [comment]
@bentsi, FYI

**Comment by yaronkaikov** [comment]
@fruch is this relevant ?

**Comment by fruch** [comment]
> @fruch is this relevant ?

I don't know if there are any other that gonna this mistake, it's a nice to have feature of falling back from string to boolean for any of the booleans in the configuration

**Comment by yaronkaikov** [comment]
@fruch is this relevant ?

**Comment by fruch** [comment]
> @fruch is this relevant ?

same answer from Jan, I think it's nice to have. but this UX doesn't seem to have been critical to anyone in the last 4 years...

**Comment by roydahan** [comment]
Closing for now until there will be a demand for it.
