### ISSUE TITLE
Build Scylla machine image on Azure

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-machine-image#54]
As we want to be able to support additional cloud provides, we be able creating Scylla machine image on Microsoft Azure platform

General plan: 

1. Define initial configuration between Azure and Jenkins (plugins , permissions, key access and act`)
2. Setting a new VM based on 20.04 OS with Scylla running on it. We should use azure CLI tool for that. installation instruction can be found at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
3. Create Azure image with packer tool (same as we do for AWS and GCE). Found some instaructions in https://microsoft.github.io/AzureTipsAndTricks/blog/tip201.html 
4. Create Jenkins pipeline for building Azure image and promotion (https://github.com/scylladb/scylla-pkg/issues/1909)
5. Create SCT artifact to test the image

**Comment by bentsi** [comment]
It is in our pipeline

**Comment by yaronkaikov** [comment]
I was asked by @penberg to do it, or at least start checking what is needed.

**Comment by roydahan** [comment]
@yaronkaikov any update on the progress here?

**Comment by yaronkaikov** [comment]
@roydahan for some reason i don't have access to Azure for about 2 weeks now. waiting for Dor to fix it for us

**Comment by fruch** [comment]
Dor is the sole admin ? I hope not...

**Comment by yaronkaikov** [comment]
@fruch looks like it,

**Comment by fruch** [comment]
> @fruch looks like it,

First order of business, I would say. Is to rectify that.
@avikivity @slivne, can you help with that ?

**Comment by avikivity** [comment]
@dorlaor ^

**Comment by dorlaor** [comment]
Ack, will do tomorrow, I struggle w/ them but it's solvable.

**Comment by yaronkaikov** [comment]
@penberg ^^

**Comment by yaronkaikov** [comment]
@slivne @penberg - I still have no access to Azure. What should i do with it?

**Comment by penberg** [comment]
(I removed lots of "ping" comments from this issue, which were making this issue hard to read.)

@bentsi @fruch Can you please comment on the plan in the issue description by @yaronkaikov to make Azure happen? Did we miss any steps.

**Comment by yaronkaikov** [comment]
Scylla currently doesn't support Azure as cloud provider , opened an issue https://github.com/scylladb/scylla/issues/8325

**Comment by tzach** [comment]
@yaronkaikov what is left to do?
Will the Azure image be part of Scylla 4.5 release?
I need the relevant details for the download page, as we did for GCP.

**Comment by yaronkaikov** [comment]
@tzach IT's not ready yet, i am working on the Scylla part (https://github.com/scylladb/scylla/issues/8325) which is under review at the moment.
It's not part of 4.5. 
Once it's ready i will provide the relevant information

**Comment by tzach** [comment]
I will be happy to get relevant info in advance, so I can start working on the download page.
I understand the name, ids etc might change later, and per release.

**Comment by yaronkaikov** [comment]
@tzach no problem. once i get the Scylla part done, and will start working on machine image part, i will update you
