### ISSUE TITLE
Latest Scylla Version not available as image

### ISSUE THREAD

**Issue by anand-chandrashekar** [scylladb/scylla-machine-image#540]
![image](https://github.com/user-attachments/assets/e85945d3-e5da-45c3-ab14-72a658c5bb61)
This [page ](https://www.scylladb.com/customer-portal/?product=ent&platform=aws&version=stable-release-2024.1)mentions that the ami version is: Amazon EC2 AMIs – ScyllaDB Version 2024.1.9

However, when we click on Node under Launch x86 column (I clicked on the one on the row for US-east-1), I found version 2024.1.5 is getting deployed. 

I can see this when I issue version command after deployment.
```
 scylla --version
2024.1.5-0.20240606.842c1b55430b
```
cc: @gcarmin @wpaven

**Comment by tzach** [comment]
@yaronkaikov please help
The AMI list match https://downloads.scylladb.com/downloads/scylla-enterprise/aws/ami/ami_ids_2024.1.9.csv

**Comment by tzach** [comment]
Issue is fix.
The root cause was a WP plugin update.
Please validate and close (if all is good).

In the long term, we will move way from WP for this, and redirect to the image list in the docs.

**Comment by anand-chandrashekar** [comment]
Looks good. Closing. Thanks @tzach 
![image](https://github.com/user-attachments/assets/8f06cf48-405d-470a-a47f-a7ff5ef0f4be)

```
   _____            _ _       _____  ____
  / ____|          | | |     |  __ \|  _ \
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ <
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/
               __/ |
              |___/

Version:
        2024.1.9-0.20240829.d583605198a7
Nodetool:
        nodetool help
CQL Shell:
        cqlsh
More documentation available at:
        https://docs.scylladb.com/
By default, Scylla sends certain information about this node to a data collection server. For more details, see https://www.scylladb.com/privacy/

    Scylla is active.
 ```
