### ISSUE TITLE
Refactor aws_io_setup class - specifically, the IO values per instance

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-machine-image#544]
My eyes hurt from seeing so many `elif'. See https://github.com/scylladb/scylla-machine-image/blob/ad01b2a28092b0488f5de443da51a51285c98a14/common/scylla_cloud_io_setup#L41 
We should store this in a dictionary, JSON or whatnot. Single location preferably.

**Comment by mykaul** [comment]
Part of this (I should open a separate issue for it!) is that we need to validate the numbers are still real. Ref https://github.com/scylladb/scylla-enterprise/issues/4713#issuecomment-2367619463
We do have a job that is testing a wide range of instances, it should probably compare the results and the hard-coded values (CC @roydahan )

**Comment by roydahan** [comment]
I created a separate issue for the above comment in qa-tasks.
