### ISSUE TITLE
Disable `scylla-fstrim.timer` during installation and maybe boot 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-machine-image#55]
seem like this timer is causing scylla-server to spin up, even if service is stopped or failed 
https://github.com/scylladb/scylla/blob/master/dist/common/systemd/scylla-fstrim.timer

we seen this happaning in scylla-cloud installation one they have a service with:
```
[Install]
WantedBy=timers.target
```

During it's installation, scylla-server would start again regardless of current state (and even is scylla-server.service is disabled)

Also could be possible root cause of #49 

I think we should disable this timer during installation, 

and maybe even during boot is user-data tells us to not boot scylla.
question is, when and whom would enable this timer back on, in this case.

**Comment by yaronkaikov** [comment]
@fruch I think it's already been done https://github.com/scylladb/scylla-machine-image/commit/9e42255ca1d5faff8f531ccc75b6c2c9ed645b5d , Is there anything else?

**Comment by fruch** [comment]
Well I guess we don't use it anymore, so there's no issue.
