### ISSUE TITLE
Consistent CPU power configuration

### ISSUE THREAD

**Issue by ebenzecri** [scylladb/scylla-machine-image#550]
I've noticed that CPU power configuration is not consistent in Scylla Cloud, which as far as I know, it's configured at AMI level. This is totally related to `cpufrequtils` and scaling governors usage.

# Scenarios
## Scenario 1: cpufrequtils is installed but using scaling governor is not supported
`cpufrequtils` is installed, but `/sys/devices/system/cpu/cpufreq/policy0/scaling_governor` doesn't exist, causing `cpufrequtils` to exit.

## Scenario 2: Using a scaling governor is supported but cpufrequtils is not installed
`/sys/devices/system/cpu/cpufreq/policy0/scaling_governor` exists but `cpufrequtils` is not installed and/or not configured as expected (as far as I know, the governor used is `performance`).

# Proposed solution
`cpufrequtils` must be always installed if using a scaling governor is possible. This must happen when the instance is bootstrapped.

**Comment by ebenzecri** [comment]
Reference: https://www.kernel.org/doc/Documentation/cpu-freq/user-guide.txt

**Comment by gmizrahi** [comment]
The idea behind slowing down the CPU is to save power (lower wattage), but we either way pay the same for the instance.
I would therefore suggest to force the CPU frequency to maximum (not the burst frequency), but still allow the CPU to burst.

**Comment by mykaul** [comment]
I believe we've implemented https://docs.aws.amazon.com/linux/al2/ug/processor_state_control.html#c-states and we do not need anything else. Am I wrong here?

**Comment by roydahan** [comment]
@yaronkaikov please check if there is work to be done here or not.

**Comment by syuu1228** [comment]
> I've noticed that CPU power configuration is not consistent in Scylla Cloud, which as far as I know, it's configured at AMI level. This is totally related to `cpufrequtils` and scaling governors usage.
> 
> # Scenarios
> ## Scenario 1: cpufrequtils is installed but using scaling governor is not supported
> `cpufrequtils` is installed, but `/sys/devices/system/cpu/cpufreq/policy0/scaling_governor` doesn't exist, causing `cpufrequtils` to exit.
> 
> ## Scenario 2: Using a scaling governor is supported but cpufrequtils is not installed
> `/sys/devices/system/cpu/cpufreq/policy0/scaling_governor` exists but `cpufrequtils` is not installed and/or not configured as expected (as far as I know, the governor used is `performance`).
> 
> # Proposed solution
> `cpufrequtils` must be always installed if using a scaling governor is possible. This must happen when the instance is bootstrapped.

I guess the problem related with this code:
```
        # On Ubuntu, we configure CPU scaling while AMI building time
        if is_redhat_variant():
            run('/opt/scylladb/scripts/scylla_cpuscaling_setup', shell=True, check=True)
```
https://github.com/scylladb/scylla-machine-image/blob/06150310c10396219e0802b62c9d1e5f0367781d/common/scylla_image_setup#L26C1-L28C89

So scylla_cpuscaling_setup is not called on our Ubuntu based AMI.
I guess the code was fine on Full version of Ubuntu AMI, but not on Ubuntu minimal.
