### ISSUE TITLE
For backward compatibility /etc/scylla/ami_configured should be crated when AMI is finished booting

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-machine-image#56]
some third-parties we're using this file to figure out the `scylla-ami-setup` is done
during the creation of `scylla-machine-image` we rename this file assuming it's only used internally

**Comment by yaronkaikov** [comment]
@fruch Is this still relevant ?

**Comment by fruch** [comment]
We seems that the cloud already handle this issue back at 4.0, on their own.

So I guess no one else is even aware about this file
