### ISSUE TITLE
Move cloud support from scylla.git to scylla-machine-image.git

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla-machine-image#59]
The cloud support code (e.g. AWS & GCE) is now in scylla.git, which does not actually need it for anything. Let's work to move that code to this repository. @avikivity points out that `scylla_setup` needs a more stable interface for that to happen.

**Comment by yaronkaikov** [comment]
Closed via https://github.com/scylladb/scylla-machine-image/pull/289/commits
