### ISSUE TITLE
Rename /etc/scylla/ami_disabled to smi_disabled

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla-machine-image#61]

**Comment by yaronkaikov** [comment]
@fruch Any idea about this? no description

**Comment by fruch** [comment]
it's talking about the old hack to disable scylla from booting

https://github.com/scylladb/scylladb/blob/72dbce8d4638964f1f0b32c2027247e7dcc4b99d/dist/common/scripts/scylla_prepare#L145

it's there from the days before using systemd, and I don't think SMI is using this option anymore (i.e. it can be remove from scylla-core)

**Comment by syuu1228** [comment]
I think this can be just drop from scylla-core, so sent PR at https://github.com/scylladb/scylladb/pull/12043 https://github.com/scylladb/scylla-machine-image/pull/412

**Comment by yaronkaikov** [comment]
> I think this can be just drop from scylla-core, so sent PR at [scylladb/scylladb#12043](https://github.com/scylladb/scylladb/pull/12043) #412

Closing
