### ISSUE TITLE
user data url broken

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-machine-image#63]
we found out that the url for getting the user data is broken on Scylla master
this is what is actually running:
`http://169.254.169.254/latest/meta-data/user-data`
it should be:
`http://169.254.169.254/latest/user-data`

**Comment by fruch** [comment]
me and @bentsi found the root cause, 
it's in scylla-core code
https://github.com/scylladb/scylla/blob/97c99ea9f344f023119823f0d627bec581d4e9ba/dist/common/scripts/scylla_util.py#L490

cause of recently refactored code.

@bentsi is creating a PR for a fix.
